In [209]:
from io import StringIO
import pandas as pd
import datacompy
import os

In [408]:
os.chdir("C:/Users/lmumelo/OneDrive - Kemri Wellcome Trust/shinyup/data")

In [526]:
df1 = pd.read_csv("CIN_DD_rev2.csv")
df2 = pd.read_csv("CIN_DD_rev3.csv")

In [527]:
df1.head()

,Variable / Field Name,Form Name,Section Header,Field Type,Field Label,"Choices, Calculations, OR Slider Labels",Field Note,Text Validation Type OR Show Slider Number,Text Validation Min,Text Validation Max,Identifier?,Branching Logic (Show field only if...),Required Field?,Custom Alignment,Question Number (surveys only),Matrix Group Name,Matrix Ranking?,Field Annotation
0,id,biodata,NaN,text,Unique ID,NaN,Use format [hosp id][record id] - eg.5100001 f...,NaN,NaN,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
1,hosp_id,biodata,NaN,dropdown,Hospital ID,"51, Kiambu DH |52, Machakos |53, Mama Lucy Kay...",NaN,NaN,NaN,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
2,depid,biodata,NaN,text,Data Entry Person ID,NaN,Eg. 02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,date_today,biodata,NaN,text,Today's Date,NaN,NaN,date_dmy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ipno,biodata,NaN,text,Patients IPNO,NaN,input -1 for empty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [528]:
df1.describe()

,Text Validation Min,Text Validation Max,Identifier?,Question Number (surveys only),Matrix Group Name,Matrix Ranking?,Field Annotation
count,11.000000,1.200000e+01,0.0,0.0,0.0,0.0,0.0
mean,4551.454545,1.667441e+05,NaN,NaN,NaN,NaN,NaN
std,15073.579173,5.773259e+05,NaN,NaN,NaN,NaN,NaN
min,0.000000,5.000000e+00,NaN,NaN,NaN,NaN,NaN
25%,0.500000,2.625000e+01,NaN,NaN,NaN,NaN,NaN
50%,3.000000,7.950000e+01,NaN,NaN,NaN,NaN,NaN
75%,15.000000,1.300000e+02,NaN,NaN,NaN,NaN,NaN
max,50000.000000,2.000000e+06,NaN,NaN,NaN,NaN,NaN

In [529]:
# df2.head()

In [530]:
df2.describe()

,Text Validation Min,Text Validation Max,Identifier?,Question Number (surveys only),Matrix Group Name,Matrix Ranking?,Field Annotation
count,1.200000e+01,1.300000e+01,0.0,0.0,0.0,0.0,0.0
mean,4.291722e+05,7.693022e+05,NaN,NaN,NaN,NaN,NaN
std,1.471000e+06,2.241768e+06,NaN,NaN,NaN,NaN,NaN
min,0.000000e+00,5.000000e+00,NaN,NaN,NaN,NaN,NaN
25%,7.500000e-01,2.800000e+01,NaN,NaN,NaN,NaN,NaN
50%,6.500000e+00,1.000000e+02,NaN,NaN,NaN,NaN,NaN
75%,2.000000e+01,1.600000e+02,NaN,NaN,NaN,NaN,NaN
max,5.100000e+06,8.000000e+06,NaN,NaN,NaN,NaN,NaN

In [531]:
print('Columns for Old CSV file: {}'.format(df1.columns))
print(' Columns for New CSV file: {}'.format(df2.columns))

Columns for Old CSV file: Index(['Variable / Field Name', 'Form Name', 'Section Header', 'Field Type',
       'Field Label', 'Choices, Calculations, OR Slider Labels', 'Field Note',
       'Text Validation Type OR Show Slider Number', 'Text Validation Min',
       'Text Validation Max', 'Identifier?',
       'Branching Logic (Show field only if...)', 'Required Field?',
       'Custom Alignment', 'Question Number (surveys only)',
       'Matrix Group Name', 'Matrix Ranking?', 'Field Annotation'],
      dtype='object')
 Columns for New CSV file: Index(['Variable / Field Name', 'Form Name', 'Section Header', 'Field Type',
       'Field Label', 'Choices, Calculations, OR Slider Labels', 'Field Note',
       'Text Validation Type OR Show Slider Number', 'Text Validation Min',
       'Text Validation Max', 'Identifier?',
       'Branching Logic (Show field only if...)', 'Required Field?',
       'Custom Alignment', 'Question Number (surveys only)',
       'Matrix Group Name', 'Matrix Ranking?', 'Field Annotation'],
      dtype='object')

In [532]:
columnA = df1.columns
columnB = df2.columns

In [533]:
for column in columnA:
    if column in columnB:
        print("These columns exist in both files")

These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files
These columns exist in both files

In [534]:
df1.equals(df2)

False

In [535]:
df2.values

array([['id', 'biodata', nan, ..., nan, nan, nan],
       ['hosp_id', 'biodata', nan, ..., nan, nan, nan],
       ['depid', 'biodata', nan, ..., nan, nan, nan],
       ...,
       ['dsc_rx5', 'discharge_information', nan, ..., nan, nan, nan],
       ['dsc_rx_other1', 'discharge_information', nan, ..., nan, nan,
        nan],
       ['dsc_rx_other2', 'discharge_information', nan, ..., nan, nan,
        nan]], dtype=object)

In [536]:
comparison_values = df1.fillna(0).isin(df2.fillna(0)) 
print (comparison_values)

     Variable / Field Name  Form Name  Section Header  Field Type  \
0                     True       True            True        True
1                     True       True            True        True
2                     True       True            True        True
3                     True       True            True        True
4                     True       True            True        True
5                     True       True            True        True
6                     True       True            True        True
7                     True       True            True        True
8                     True       True            True        True
9                    False       True            True        True
10                   False       True            True       False
11                   False       True            True        True
12                   False       True            True        True
13                   False       True            True        True
14                   False       True            True       False
15                   False       True            True       False
16                   False       True            True        True
17                   False       True            True       False
18                   False       True            True       False
19                   False       True            True       False
20                   False       True            True        True
21                   False       True            True       False
22                   False       True            True        True
23                   False       True            True        True
24                   False       True            True        True
25                   False       True            True       False
26                   False      False           False       False
27                   False      False            True       False
28                   False       True           False        True
29                   False       True            True        True
..                     ...        ...             ...         ...
281                  False       True            True        True
282                  False       True            True        True
283                  False       True            True       False
284                  False       True            True        True
285                  False       True            True        True
286                  False       True            True        True
287                  False       True            True       False
288                  False       True           False       False
289                  False       True            True        True
290                  False       True            True        True
291                  False       True            True       False
292                  False       True           False       False
293                  False       True            True        True
294                  False       True            True        True
295                  False       True            True        True
296                  False       True            True       False
297                  False       True            True        True
298                  False       True            True        True
299                  False       True            True        True
300                  False       True            True       False
301                  False       True            True       False
302                  False       True            True       False
303                  False       True           False       False
304                  False       True            True        True
305                  False       True            True       False
306                  False       True            True       False
307                  False       True           False       False
308                  False       True            True        True
309                  False       True            True       False
310                  False       True            True       False

     Field Label  Choices, Calculations, OR Slider Labels  Field Note  \
0           True                                     True        True
1           True                                    False        True
2           True                                     True        True
3           True                                     True        True
4           True                                     True        True
5           True                                     True        True
6           True                                     True        True
7           True                                     True        True
8           True                                     True        True
9          False                                     True       False
10         False                                    False       False
11         False                                     True       False
12         False                                     True        True
13         False                                     True       False
14         False                                    False       False
15         False                                    False       False
16         False                                     True       False
17         False                                    False        True
18         False                                    False       False
19         False                                    False        True
20         False                                    False        True
21         False                                    False        True
22         False                                     True        True
23         False                                    False        True
24         False                                    False        True
25         False                                    False        True
26         False                                    False       False
27         False                                    False        True
28         False                                     True       False
29         False                                     True        True
..           ...                                      ...         ...
281        False                                    False        True
282        False                                    False        True
283        False                                    False        True
284        False                                    False        True
285        False                                    False        True
286        False                                    False        True
287        False                                     True        True
288        False                                    False        True
289        False                                    False        True
290        False                                    False        True
291        False                                    False        True
292        False                                    False        True
293        False                                    False        True
294        False                                    False        True
295        False                                    False        True
296        False                                    False        True
297        False                                    False        True
298        False                                    False        True
299        False                                    False        True
300        False                                    False        True
301        False                                    False        True
302        False                                    False        True
303        False                                    False        True
304        False                                    False        True
305        False                                    False        True
306        False                                    False        True
307        False                                    False        True
308        False                                     True        True
309        False                                    False        True
310        False                                    False        True

     Text Validation Type OR Show Slider Number  Text Validation Min  \
0                                         False                False
1                                          True                 True
2                                          True                 True
3                                          True                 True
4                                          True                 True
5                                          True                 True
6                                          True                 True
7                                          True                 True
8                                          True                 True
9                                         False                 True
10                                         True                 True
11                                        False                 True
12                                         True                 True
13                                        False                False
14                                        False                False
15                                        False                False
16                                         True                False
17                                         True                 True
18                                        False                 True
19                                         True                 True
20                                         True                 True
21                                         True                 True
22                                         True                 True
23                                         True                 True
24                                         True                 True
25                                         True                 True
26                                        False                 True
27                                         True                 True
28                                         True                 True
29                                         True                 True
..                                          ...                  ...
281                                        True                 True
282                                        True                 True
283                                        True                 True
284                                        True                 True
285                                        True                 True
286                                        True                 True
287                                        True                 True
288                                        True                 True
289                                        True                 True
290                                        True                 True
291                                        True                 True
292                                        True                 True
293                                        True                 True
294                                        True                 True
295                                        True                 True
296                                        True                 True
297                                        True                 True
298                                        True                 True
299                                        True                 True
300                                        True                 True
301                                        True                 True
302                                        True                 True
303                                        True                 True
304                                        True                 True
305                                        True                 True
306                                        True                 True
307                                        True                 True
308                                        True                 True
309                                        True                 True
310                                        True                 True

     Text Validation Max  Identifier?  \
0                  False         True
1                   True         True
2                   True         True
3                   True         True
4                   True         True
5                   True         True
6                   True         True
7                   True         True
8                   True         True
9                   True         True
10                  True         True
11                  True         True
12                  True         True
13                 False         True
14                 False         True
15                 False         True
16                 False         True
17                  True         True
18                  True         True
19                  True         True
20                  True         True
21                  True         True
22                  True         True
23                  True         True
24                  True         True
25                  True         True
26                 False         True
27                  True         True
28                 False         True
29                  True         True
..                   ...          ...
281                 True         True
282                 True         True
283                 True         True
284                 True         True
285                 True         True
286                 True         True
287                 True         True
288                 True         True
289                 True         True
290                 True         True
291                 True         True
292                 True         True
293                 True         True
294                 True         True
295                 True         True
296                 True         True
297                 True         True
298                 True         True
299                 True         True
300                 True         True
301                 True         True
302                 True         True
303                 True         True
304                 True         True
305                 True         True
306                 True         True
307                 True         True
308                 True         True
309                 True         True
310                 True         True

     Branching Logic (Show field only if...)  Required Field?  \
0                                       True             True
1                                       True             True
2                                       True             True
3                                       True             True
4                                       True             True
5                                       True             True
6                                       True             True
7                                       True             True
8                                       True             True
9                                       True             True
10                                      True            False
11                                     False            False
12                                      True            False
13                                     False             True
14                                      True            False
15                                      True            False
16                                      True            False
17                                      True             True
18                                      True            False
19                                     False             True
20                                     False             True
21                                     False             True
22                                      True             True
23                                      True             True
24                                     False             True
25                                     False             True
26                                     False            False
27                                      True            False
28                                     False            False
29                                      True             True
..                                       ...              ...
281                                     True             True
282                                     True             True
283                                     True             True
284                                     True             True
285                                     True             True
286                                     True             True
287                                     True             True
288                                     True             True
289                                    False             True
290                                    False             True
291                                    False             True
292                                    False             True
293                                     True             True
294                                     True             True
295                                     True             True
296                                     True             True
297                                     True             True
298                                     True             True
299                                     True             True
300                                     True             True
301                                    False             True
302                                    False             True
303                                    False             True
304                                    False             True
305                                    False             True
306                                    False             True
307                                    False             True
308                                     True             True
309                                     True             True
310                                     True             True

     Custom Alignment  Question Number (surveys only)  Matrix Group Name  \
0                True                            True               True
1                True                            True               True
2                True                            True               True
3                True                            True               True
4                True                            True               True
5                True                            True               True
6                True                            True               True
7                True                            True               True
8                True                            True               True
9                True                            True               True
10              False                            True               True
11              False                            True               True
12              False                            True               True

In [537]:
import numpy as np
rows,cols=np.where(comparison_values==False)

In [538]:
for item in zip(rows,cols):
    df1.iloc[item[0], item[1]] = '{} --> {}'.format(df1.iloc[item[0], item[1]],df2.iloc[item[0], item[1]])

In [539]:
df1

,Variable / Field Name,Form Name,Section Header,Field Type,Field Label,"Choices, Calculations, OR Slider Labels",Field Note,Text Validation Type OR Show Slider Number,Text Validation Min,Text Validation Max,Identifier?,Branching Logic (Show field only if...),Required Field?,Custom Alignment,Question Number (surveys only),Matrix Group Name,Matrix Ranking?,Field Annotation
0,id,biodata,NaN,text,Unique ID,NaN,Use format [hosp id][record id] - eg.5100001 f...,nan --> integer,nan --> 5100000.0,nan --> 8000000.0,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
1,hosp_id,biodata,NaN,dropdown,Hospital ID,"51, Kiambu DH |52, Machakos |53, Mama Lucy Kay...",NaN,NaN,NaN,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
2,depid,biodata,NaN,text,Data Entry Person ID,NaN,Eg. 02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,date_today,biodata,NaN,text,Today's Date,NaN,NaN,date_dmy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ipno,biodata,NaN,text,Patients IPNO,NaN,input -1 for empty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,age_years,biodata,NaN,text,Age (years),NaN,input -1 for empty,number,0,5,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
6,age_mths,biodata,NaN,text,Age (months),NaN,input -1 for empty,number,2,59,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
7,age_less1mnth,biodata,NaN,yesno,Age less than 1 month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
8,age_days,biodata,NaN,text,Age (Days),NaN,input -1 for empty,number,0,28,NaN,[age_less1mnth]='1',NaN,NaN,NaN,NaN,NaN,NaN
9,date_adm --> res_loc,biodata,NaN,text,Admission Date --> Residence - Location,NaN,(For Empty Date type 01/01/1912) --> Input -1 ...,date_dmy --> nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,ref_hosp --> res_dst,biodata,NaN,radio --> text,Referred to hospital? --> Residence - District,"1,Yes |0, No| -1, Empty --> nan",nan --> Input -1 for empty,NaN,NaN,NaN,NaN,NaN,y --> nan,RH --> nan,NaN,NaN,NaN,NaN
11,ref_hosp_spec --> date_adm,biodata,NaN,text,Referred from which facility? --> Admission Date,NaN,nan --> (For Empty Date type 01/01/1913),nan --> date_dmy,NaN,NaN,NaN,[ref_hosp] = '1' --> nan,y --> nan,RH --> nan,NaN,NaN,NaN,NaN
12,readm_hosp --> ref_hosp,biodata,NaN,radio,Re-admission to this hospital? --> Referred to...,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,NaN,NaN,nan --> y,nan --> RH,NaN,NaN,NaN,NaN
13,weight --> ref_hosp_spec,biodata,NaN,text,Weight (kgs) --> Referred from which facility?,NaN,kgs ( enter -1 if not recorded) --> nan,number --> nan,3.0 --> nan,30.0 --> nan,NaN,nan --> [ref_hosp] = '1',y,nan --> RH,NaN,NaN,NaN,NaN
14,height --> readm_hosp,biodata,NaN,text --> radio,Height / Length (cm) --> Re-admission to this ...,"nan --> 1,Yes |0, No| -1, Empty",cm; ( enter -1 if not recorded) --> nan,number --> nan,20.0 --> nan,120.0 --> nan,NaN,NaN,y --> nan,NaN,NaN,NaN,NaN,NaN
15,whz --> weight,biodata,NaN,dropdown --> text,Weight-Height Z score --> Weight (kgs),"1, 3SD | 2, 2SD | 3, 1SD | 4, 0SD | 5, -1SD | ...",nan --> kgs ( enter -1 if not recorded),nan --> number,nan --> 3.0,nan --> 30.0,NaN,NaN,nan --> y,NaN,NaN,NaN,NaN,NaN
16,muac --> height,biodata,NaN,text,MUAC (Mid-upper arm circumference) in cm --> H...,NaN,(enter -1 if not recorded) --> cm; ( enter -1 ...,number,nan --> 20.0,nan --> 120.0,NaN,NaN,y --> nan,NaN,NaN,NaN,NaN,NaN
17,child_sex --> whz,biodata,NaN,radio --> dropdown,Gender --> Weight-Height Z score,"0, Female | 1, Male | -1, Empty --> 1, 3SD | 2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,RH --> nan,NaN,NaN,NaN,NaN
18,vacc_source --> muac,biodata,NaN,radio --> text,Vaccination data source --> MUAC (Mid-upper ar...,"1, PAR | 2, Free text --> nan",nan --> (enter -1 if not recorded),nan --> number,NaN,NaN,NaN,NaN,nan --> y,NaN,NaN,NaN,NaN,NaN
19,vacc_status_text --> child_sex,biodata,NaN,dropdown --> radio,Vaccination status from text --> Gender,"1, Vaccination upto date for age(or as per KEP...",NaN,NaN,NaN,NaN,NaN,[vacc_source]='2' --> nan,NaN,nan --> RH,NaN,NaN,NaN,NaN
20,vacc_opv_penta --> vacc_source,biodata,NaN,radio,Number of doses of OPV/Penta --> Vaccination ...,"0, 0| 1,1|2,2| 3,3|-1, Empty --> 1, PAR | 2, F...",NaN,NaN,NaN,NaN,NaN,[vacc_source]='1' --> nan,NaN,RH --> nan,NaN,NaN,NaN,NaN
21,pcv10 --> vacc_status_text,biodata,NaN,radio --> dropdown,Number of doses of PCV 10 (Pneumococcal vaccin...,"0, 0| 1,1|2,2| 3,3|-1, Empty --> 1, Vaccinatio...",NaN,NaN,NaN,NaN,NaN,[vacc_source]='1' --> [vacc_source]='2',NaN,RH --> nan,NaN,NaN,NaN,NaN
22,rotavirus --> vacc_opv_penta,biodata,NaN,radio,Number of doses of Rota virus given --> Number...,"0, 0| 1,1|2,2| 3,3|-1, Empty",NaN,NaN,NaN,NaN,NaN,[vacc_source]='1',NaN,RH,NaN,NaN,NaN,NaN
23,bcg --> pcv10,biodata,NaN,radio,BCG given --> Number of doses of PCV 10 (Pneum...,"1,Yes |0, No| -1, Empty --> 0, 0| 1,1|2,2| 3,...",NaN,NaN,NaN,NaN,NaN,[vacc_source]='1',NaN,RH,NaN,NaN,NaN,NaN
24,measles --> rotavirus,biodata,NaN,radio,Measles given --> Number of doses of Rota viru...,"1,Yes |0, No| -1, Empty --> 0, 0| 1,1|2,2| 3,...",NaN,NaN,NaN,NaN,NaN,[vacc_source]='1' --> [vacc_source] = '1' and ...,NaN,RH,NaN,NaN,NaN,NaN
25,par --> bcg,biodata,NaN,yesno --> radio,PAR used --> BCG given,"nan --> 1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,NaN,nan --> [vacc_source]='1',NaN,RH,NaN,NaN,NaN,NaN
26,lo_illness_ --> measles,history --> biodata,<h1><font color=blue>HISTORY</font></h1> --> nan,text --> radio,Length of illness (days) --> Measles given,"nan --> 1,Yes |0, No| -1, Empty",indicate the duration for longest presenting c...,number --> nan,0,21.0 --> nan,NaN,nan --> [vacc_source]='1',y --> nan,nan --> RH,NaN,NaN,NaN,NaN
27,fever --> par,history --> biodata,NaN,radio --> yesno,Fever --> PAR used,"1,Yes |0, No| -1, Empty --> nan",NaN,NaN,NaN,NaN,NaN,NaN,y --> nan,RH,NaN,NaN,NaN,NaN
28,fever_dur --> lo_illness_,history,nan --> <h1><font color=blue>HISTORY</font></h1>,text,Fever duration --> Length of illness (days),NaN,indicate in days --> indicate the duration for...,number,NaN,nan --> 21.0,NaN,[fever]='1' --> nan,nan --> y,NaN,NaN,NaN,NaN,NaN
29,cough --> fever,history,NaN,radio,Cough --> Fever,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,NaN,NaN,y,RH,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,dsc_dx1_malnutr --> dsc_dx1_pneum,discharge_information,NaN,dropdown,Malnutrition --> Pneumonia,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwas...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,dsc_dx1_anaemia --> dsc_dx1_diarrhoea,discharge_information,NaN,dropdown,Anaemia --> Diarrhoea / Acute GE (Gastro-Enter...,"1, Severe|2, Non Severe | 3, No classification...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,dsc_dx1_meningitis --> dsc_dx1_dehydrat,discharge_information,NaN,yesno --> dropdown,Meningitis --> Dehydration,"nan --> 1,Shock |2, Severe | 3, Some|4, No Cla...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,RH --> nan,NaN,NaN,NaN,NaN
284,dsc_dx1_asthma --> dsc_dx1_hiv,discharge_information,NaN,dropdown,Asthma --> HIV / AIDS,"1,Very Severe | 2, Severe |3, Non Severe (mild...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,dsc_dx1_tb --> dsc_dx1_malnutr,discharge_information,NaN,dropdown,TB --> Malnutrition,"1, PTB | 2, Extra-Pulmonary --> 1,Kwashiorkor ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,RH --> nan,NaN,NaN,NaN,NaN
286,dsc_dx1_other_1 --> dsc_dx1_anaemia,discharge_information,NaN,dropdown,Other Primary discharge diagnoses 1 --> Anaemia,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,dsc_dx1_other_2 --> dsc_dx1_meningitis,discharge_information,NaN,text --> yesno,Other Primary discharge diagnoses 2 --> Menin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan --> RH,NaN,NaN,NaN,NaN
288,dsc_dx2 --> dsc_dx1_asthma,discharge_information,Secondary diagnosis (Enter all other diagnosis...,yesno --> dropdown,Is there a secondary diagnosis? --> Asthma,"nan --> 1,Very Severe | 2, Severe |3, Non Seve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,RH --> nan,NaN,NaN,NaN,NaN
289,dsc_dx2_malaria --> dsc_dx1_tb,discharge_information,NaN,dropdown,Malaria --> TB,"1,Severe | 2, Non severe |3, Non Classified --...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1' --> nan,NaN,nan --> RH,NaN,NaN,NaN,NaN
290,dsc_dx2_pneum --> dsc_dx1_other_1,discharge_information,NaN,dropdown,Pneumonia --> Other Primary discharge diagnose...,"1,Very Severe | 2, Severe |3, Non Severe |4,No...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1' --> nan,NaN,NaN,NaN,NaN,NaN,NaN
291,dsc_dx2_diarrhoea --> dsc_dx1_other_2,discharge_information,NaN,dropdown --> text,Diarrhoea / Acute GE (Gastro-Enteritis) --> Ot...,"1,Non-bloody | 2, bloody | 3, No classificatio...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1' --> nan,NaN,NaN,NaN,NaN,NaN,NaN
292,dsc_dx2_dehydrat --> dsc_dx2,discharge_information,nan --> Secondary diagnosis (Enter all other d...,dropdown --> yesno,Dehydration --> Is there a secondary diagnosis?,"1,Shock |2, Severe | 3, Some|4, No Classificat...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1' --> nan,NaN,nan --> RH,NaN,NaN,NaN,NaN
293,dsc_dx2_hiv --> dsc_dx2_malaria,discharge_information,NaN,dropdown,HIV / AIDS --> Malaria,"1,Known | 2, Possible --> 1,Severe | 2, Non se...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
294,dsc_dx2_malnutr --> dsc_dx2_pneum,discharge_information,NaN,dropdown,Malnutrition --> Pneumonia,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwas...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
295,dsc_dx2_anaemia --> dsc_dx2_diarrhoea,discharge_information,NaN,dropdown,Anaemia --> Diarrhoea / Acute GE (Gastro-Enter...,"1, Severe|2, Non Severe | 3, No classification...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
296,dsc_dx2_meningitis --> dsc_dx2_dehydrat,discharge_information,NaN,yesno --> dropdown,Meningitis --> Dehydration,"nan --> 1,Shock |2, Severe | 3, Some|4, No Cla...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH --> nan,NaN,NaN,NaN,NaN
297,dsc_dx2_asthma --> dsc_dx2_hiv,discharge_information,NaN,dropdown,Asthma --> HIV / AIDS,"1,Very Severe | 2, Severe |3, Non Severe (mild...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
298,dsc_dx2_tb --> dsc_dx2_malnutr,discharge_information,NaN,dropdown,TB --> Malnutrition,"1, PTB | 2, Extra-Pulmonary --> 1,Kwashiorkor ...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH --> nan,NaN,NaN,NaN,NaN
299,dsc_dx2_other_1 --> dsc_dx2_anaemia,discharge_information,NaN,dropdown,Other secondary discharge diagnoses 1 --> Ana...,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
300,dsc_dx2_other_2 --> dsc_dx2_meningitis,discharge_information,NaN,dropdown --> yesno,Other secondary discharge diagnoses 2 --> Men...,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,nan --> RH,NaN,NaN,NaN,NaN
301,dsc_dx2_other_3 --> dsc_dx2_asthma,discharge_information,NaN,text --> dropdown,Other secondary discharge diagnoses 3 --> Asthma,"nan --> 1,Very Severe | 2, Severe |3, Non Seve...",NaN,NaN,NaN,NaN,NaN,nan --> [dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
302,dsc_dx2_other_4 --> dsc_dx2_tb,discharge_information,NaN,text --> dropdown,Other secondary discharge diagnoses 4 --> TB,"nan --> 1, PTB | 2, Extra-Pulmonary",NaN,NaN,NaN,NaN,NaN,nan --> [dsc_dx2] = '1',NaN,nan --> RH,NaN,NaN,NaN,NaN
303,dsc_rx --> dsc_dx2_other_1,discharge_information,Discharge treatment --> nan,yesno --> dropdown,Discharge treatment prescribed --> Other secon...,"nan --> 2, ACUTE ABDOMEN | 3, Adenoid Hypentro...",NaN,NaN,NaN,NaN,NaN,nan --> [dsc_dx2] = '1',NaN,RH --> nan,NaN,NaN,NaN,NaN
304,dsc_rx1 --> dsc_dx2_other_2,discharge_information,NaN,dropdown,Discharge treatment1 --> Other secondary disch...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,NaN,[dsc_rx]='1' --> [dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
305,dsc_rx2 --> dsc_dx2_other_3,discharge_information,NaN,dropdown --> text,Discharge treatment2 --> Other secondary disc...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,NaN,[dsc_rx]='1' --> nan,NaN,NaN,NaN,NaN,NaN,NaN
306,dsc_rx3 --> dsc_dx2_other_4,discharge_information,NaN,dropdown --> text,Discharge treatment3 --> Other secondary disc...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,NaN,[dsc_rx]='1' --> nan,NaN,NaN,NaN,NaN,NaN,NaN
307,dsc_rx4 --> dsc_rx,discharge_information,nan --> Discharge treatment,dropdown --> yesno,Discharge treatment4 --> Discharge treatment p...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,NaN,[dsc_rx]='1' --> nan,NaN,nan --> RH,NaN,NaN,NaN,NaN
308,dsc_rx5 --> dsc_rx1,discharge_information,NaN,dropdown,Discharge treatment5 --> Discharge treatment1,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,NaN,[dsc_rx]='1',NaN,NaN,NaN,NaN,NaN,NaN
309,dsc_rx_other1 --> dsc_rx2,discharge_information,NaN,text --> dropdown,Discharge treatment_other1 --> Discharge treat...,"nan --> 1, Amodiaquine|2,Coartem |3, Albendazo...",NaN,NaN,NaN,NaN,NaN,[dsc_rx]='1',NaN,NaN,NaN,NaN,NaN,NaN
310,dsc_rx_other2 --> dsc_rx3,discharge_information,NaN,text --> dropdown,Discharge treatment_other2 --> Discharge treat...,"nan --> 1, Amodiaquine|2,Coartem |3, Albendazo...",NaN,NaN,NaN,NaN,NaN,[dsc_rx]='1',NaN,NaN,NaN,NaN,NaN,NaN

In [540]:
df1.dropna(axis=1, how='all')

,Variable / Field Name,Form Name,Section Header,Field Type,Field Label,"Choices, Calculations, OR Slider Labels",Field Note,Text Validation Type OR Show Slider Number,Text Validation Min,Text Validation Max,Branching Logic (Show field only if...),Required Field?,Custom Alignment
0,id,biodata,NaN,text,Unique ID,NaN,Use format [hosp id][record id] - eg.5100001 f...,nan --> integer,nan --> 5100000.0,nan --> 8000000.0,NaN,y,NaN
1,hosp_id,biodata,NaN,dropdown,Hospital ID,"51, Kiambu DH |52, Machakos |53, Mama Lucy Kay...",NaN,NaN,NaN,NaN,NaN,y,NaN
2,depid,biodata,NaN,text,Data Entry Person ID,NaN,Eg. 02,NaN,NaN,NaN,NaN,NaN,NaN
3,date_today,biodata,NaN,text,Today's Date,NaN,NaN,date_dmy,NaN,NaN,NaN,NaN,NaN
4,ipno,biodata,NaN,text,Patients IPNO,NaN,input -1 for empty,NaN,NaN,NaN,NaN,NaN,NaN
5,age_years,biodata,NaN,text,Age (years),NaN,input -1 for empty,number,0,5,NaN,y,NaN
6,age_mths,biodata,NaN,text,Age (months),NaN,input -1 for empty,number,2,59,NaN,y,NaN
7,age_less1mnth,biodata,NaN,yesno,Age less than 1 month,NaN,NaN,NaN,NaN,NaN,NaN,y,NaN
8,age_days,biodata,NaN,text,Age (Days),NaN,input -1 for empty,number,0,28,[age_less1mnth]='1',NaN,NaN
9,date_adm --> res_loc,biodata,NaN,text,Admission Date --> Residence - Location,NaN,(For Empty Date type 01/01/1912) --> Input -1 ...,date_dmy --> nan,NaN,NaN,NaN,NaN,NaN
10,ref_hosp --> res_dst,biodata,NaN,radio --> text,Referred to hospital? --> Residence - District,"1,Yes |0, No| -1, Empty --> nan",nan --> Input -1 for empty,NaN,NaN,NaN,NaN,y --> nan,RH --> nan
11,ref_hosp_spec --> date_adm,biodata,NaN,text,Referred from which facility? --> Admission Date,NaN,nan --> (For Empty Date type 01/01/1913),nan --> date_dmy,NaN,NaN,[ref_hosp] = '1' --> nan,y --> nan,RH --> nan
12,readm_hosp --> ref_hosp,biodata,NaN,radio,Re-admission to this hospital? --> Referred to...,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,NaN,nan --> y,nan --> RH
13,weight --> ref_hosp_spec,biodata,NaN,text,Weight (kgs) --> Referred from which facility?,NaN,kgs ( enter -1 if not recorded) --> nan,number --> nan,3.0 --> nan,30.0 --> nan,nan --> [ref_hosp] = '1',y,nan --> RH
14,height --> readm_hosp,biodata,NaN,text --> radio,Height / Length (cm) --> Re-admission to this ...,"nan --> 1,Yes |0, No| -1, Empty",cm; ( enter -1 if not recorded) --> nan,number --> nan,20.0 --> nan,120.0 --> nan,NaN,y --> nan,NaN
15,whz --> weight,biodata,NaN,dropdown --> text,Weight-Height Z score --> Weight (kgs),"1, 3SD | 2, 2SD | 3, 1SD | 4, 0SD | 5, -1SD | ...",nan --> kgs ( enter -1 if not recorded),nan --> number,nan --> 3.0,nan --> 30.0,NaN,nan --> y,NaN
16,muac --> height,biodata,NaN,text,MUAC (Mid-upper arm circumference) in cm --> H...,NaN,(enter -1 if not recorded) --> cm; ( enter -1 ...,number,nan --> 20.0,nan --> 120.0,NaN,y --> nan,NaN
17,child_sex --> whz,biodata,NaN,radio --> dropdown,Gender --> Weight-Height Z score,"0, Female | 1, Male | -1, Empty --> 1, 3SD | 2...",NaN,NaN,NaN,NaN,NaN,NaN,RH --> nan
18,vacc_source --> muac,biodata,NaN,radio --> text,Vaccination data source --> MUAC (Mid-upper ar...,"1, PAR | 2, Free text --> nan",nan --> (enter -1 if not recorded),nan --> number,NaN,NaN,NaN,nan --> y,NaN
19,vacc_status_text --> child_sex,biodata,NaN,dropdown --> radio,Vaccination status from text --> Gender,"1, Vaccination upto date for age(or as per KEP...",NaN,NaN,NaN,NaN,[vacc_source]='2' --> nan,NaN,nan --> RH
20,vacc_opv_penta --> vacc_source,biodata,NaN,radio,Number of doses of OPV/Penta --> Vaccination ...,"0, 0| 1,1|2,2| 3,3|-1, Empty --> 1, PAR | 2, F...",NaN,NaN,NaN,NaN,[vacc_source]='1' --> nan,NaN,RH --> nan
21,pcv10 --> vacc_status_text,biodata,NaN,radio --> dropdown,Number of doses of PCV 10 (Pneumococcal vaccin...,"0, 0| 1,1|2,2| 3,3|-1, Empty --> 1, Vaccinatio...",NaN,NaN,NaN,NaN,[vacc_source]='1' --> [vacc_source]='2',NaN,RH --> nan
22,rotavirus --> vacc_opv_penta,biodata,NaN,radio,Number of doses of Rota virus given --> Number...,"0, 0| 1,1|2,2| 3,3|-1, Empty",NaN,NaN,NaN,NaN,[vacc_source]='1',NaN,RH
23,bcg --> pcv10,biodata,NaN,radio,BCG given --> Number of doses of PCV 10 (Pneum...,"1,Yes |0, No| -1, Empty --> 0, 0| 1,1|2,2| 3,...",NaN,NaN,NaN,NaN,[vacc_source]='1',NaN,RH
24,measles --> rotavirus,biodata,NaN,radio,Measles given --> Number of doses of Rota viru...,"1,Yes |0, No| -1, Empty --> 0, 0| 1,1|2,2| 3,...",NaN,NaN,NaN,NaN,[vacc_source]='1' --> [vacc_source] = '1' and ...,NaN,RH
25,par --> bcg,biodata,NaN,yesno --> radio,PAR used --> BCG given,"nan --> 1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,nan --> [vacc_source]='1',NaN,RH
26,lo_illness_ --> measles,history --> biodata,<h1><font color=blue>HISTORY</font></h1> --> nan,text --> radio,Length of illness (days) --> Measles given,"nan --> 1,Yes |0, No| -1, Empty",indicate the duration for longest presenting c...,number --> nan,0,21.0 --> nan,nan --> [vacc_source]='1',y --> nan,nan --> RH
27,fever --> par,history --> biodata,NaN,radio --> yesno,Fever --> PAR used,"1,Yes |0, No| -1, Empty --> nan",NaN,NaN,NaN,NaN,NaN,y --> nan,RH
28,fever_dur --> lo_illness_,history,nan --> <h1><font color=blue>HISTORY</font></h1>,text,Fever duration --> Length of illness (days),NaN,indicate in days --> indicate the duration for...,number,NaN,nan --> 21.0,[fever]='1' --> nan,nan --> y,NaN
29,cough --> fever,history,NaN,radio,Cough --> Fever,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,NaN,y,RH
...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,dsc_dx1_malnutr --> dsc_dx1_pneum,discharge_information,NaN,dropdown,Malnutrition --> Pneumonia,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwas...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,dsc_dx1_anaemia --> dsc_dx1_diarrhoea,discharge_information,NaN,dropdown,Anaemia --> Diarrhoea / Acute GE (Gastro-Enter...,"1, Severe|2, Non Severe | 3, No classification...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,dsc_dx1_meningitis --> dsc_dx1_dehydrat,discharge_information,NaN,yesno --> dropdown,Meningitis --> Dehydration,"nan --> 1,Shock |2, Severe | 3, Some|4, No Cla...",NaN,NaN,NaN,NaN,NaN,NaN,RH --> nan
284,dsc_dx1_asthma --> dsc_dx1_hiv,discharge_information,NaN,dropdown,Asthma --> HIV / AIDS,"1,Very Severe | 2, Severe |3, Non Severe (mild...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,dsc_dx1_tb --> dsc_dx1_malnutr,discharge_information,NaN,dropdown,TB --> Malnutrition,"1, PTB | 2, Extra-Pulmonary --> 1,Kwashiorkor ...",NaN,NaN,NaN,NaN,NaN,NaN,RH --> nan
286,dsc_dx1_other_1 --> dsc_dx1_anaemia,discharge_information,NaN,dropdown,Other Primary discharge diagnoses 1 --> Anaemia,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,dsc_dx1_other_2 --> dsc_dx1_meningitis,discharge_information,NaN,text --> yesno,Other Primary discharge diagnoses 2 --> Menin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan --> RH
288,dsc_dx2 --> dsc_dx1_asthma,discharge_information,Secondary diagnosis (Enter all other diagnosis...,yesno --> dropdown,Is there a secondary diagnosis? --> Asthma,"nan --> 1,Very Severe | 2, Severe |3, Non Seve...",NaN,NaN,NaN,NaN,NaN,NaN,RH --> nan
289,dsc_dx2_malaria --> dsc_dx1_tb,discharge_information,NaN,dropdown,Malaria --> TB,"1,Severe | 2, Non severe |3, Non Classified --...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1' --> nan,NaN,nan --> RH
290,dsc_dx2_pneum --> dsc_dx1_other_1,discharge_information,NaN,dropdown,Pneumonia --> Other Primary discharge diagnose...,"1,Very Severe | 2, Severe |3, Non Severe |4,No...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1' --> nan,NaN,NaN
291,dsc_dx2_diarrhoea --> dsc_dx1_other_2,discharge_information,NaN,dropdown --> text,Diarrhoea / Acute GE (Gastro-Enteritis) --> Ot...,"1,Non-bloody | 2, bloody | 3, No classificatio...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1' --> nan,NaN,NaN
292,dsc_dx2_dehydrat --> dsc_dx2,discharge_information,nan --> Secondary diagnosis (Enter all other d...,dropdown --> yesno,Dehydration --> Is there a secondary diagnosis?,"1,Shock |2, Severe | 3, Some|4, No Classificat...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1' --> nan,NaN,nan --> RH
293,dsc_dx2_hiv --> dsc_dx2_malaria,discharge_information,NaN,dropdown,HIV / AIDS --> Malaria,"1,Known | 2, Possible --> 1,Severe | 2, Non se...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN
294,dsc_dx2_malnutr --> dsc_dx2_pneum,discharge_information,NaN,dropdown,Malnutrition --> Pneumonia,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwas...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN
295,dsc_dx2_anaemia --> dsc_dx2_diarrhoea,discharge_information,NaN,dropdown,Anaemia --> Diarrhoea / Acute GE (Gastro-Enter...,"1, Severe|2, Non Severe | 3, No classification...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN
296,dsc_dx2_meningitis --> dsc_dx2_dehydrat,discharge_information,NaN,yesno --> dropdown,Meningitis --> Dehydration,"nan --> 1,Shock |2, Severe | 3, Some|4, No Cla...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH --> nan
297,dsc_dx2_asthma --> dsc_dx2_hiv,discharge_information,NaN,dropdown,Asthma --> HIV / AIDS,"1,Very Severe | 2, Severe |3, Non Severe (mild...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN
298,dsc_dx2_tb --> dsc_dx2_malnutr,discharge_information,NaN,dropdown,TB --> Malnutrition,"1, PTB | 2, Extra-Pulmonary --> 1,Kwashiorkor ...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH --> nan
299,dsc_dx2_other_1 --> dsc_dx2_anaemia,discharge_information,NaN,dropdown,Other secondary discharge diagnoses 1 --> Ana...,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN
300,dsc_dx2_other_2 --> dsc_dx2_meningitis,discharge_information,NaN,dropdown --> yesno,Other secondary discharge diagnoses 2 --> Men...,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,nan --> RH
301,dsc_dx2_other_3 --> dsc_dx2_asthma,discharge_information,NaN,text --> dropdown,Other secondary discharge diagnoses 3 --> Asthma,"nan --> 1,Very Severe | 2, Severe |3, Non Seve...",NaN,NaN,NaN,NaN,nan --> [dsc_dx2] = '1',NaN,NaN
302,dsc_dx2_other_4 --> dsc_dx2_tb,discharge_information,NaN,text --> dropdown,Other secondary discharge diagnoses 4 --> TB,"nan --> 1, PTB | 2, Extra-Pulmonary",NaN,NaN,NaN,NaN,nan --> [dsc_dx2] = '1',NaN,nan --> RH
303,dsc_rx --> dsc_dx2_other_1,discharge_information,Discharge treatment --> nan,yesno --> dropdown,Discharge treatment prescribed --> Other secon...,"nan --> 2, ACUTE ABDOMEN | 3, Adenoid Hypentro...",NaN,NaN,NaN,NaN,nan --> [dsc_dx2] = '1',NaN,RH --> nan
304,dsc_rx1 --> dsc_dx2_other_2,discharge_information,NaN,dropdown,Discharge treatment1 --> Other secondary disch...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,[dsc_rx]='1' --> [dsc_dx2] = '1',NaN,NaN
305,dsc_rx2 --> dsc_dx2_other_3,discharge_information,NaN,dropdown --> text,Discharge treatment2 --> Other secondary disc...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,[dsc_rx]='1' --> nan,NaN,NaN
306,dsc_rx3 --> dsc_dx2_other_4,discharge_information,NaN,dropdown --> text,Discharge treatment3 --> Other secondary disc...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,[dsc_rx]='1' --> nan,NaN,NaN
307,dsc_rx4 --> dsc_rx,discharge_information,nan --> Discharge treatment,dropdown --> yesno,Discharge treatment4 --> Discharge treatment p...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,[dsc_rx]='1' --> nan,NaN,nan --> RH
308,dsc_rx5 --> dsc_rx1,discharge_information,NaN,dropdown,Discharge treatment5 --> Discharge treatment1,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,[dsc_rx]='1',NaN,NaN
309,dsc_rx_other1 --> dsc_rx2,discharge_information,NaN,text --> dropdown,Discharge treatment_other1 --> Discharge treat...,"nan --> 1, Amodiaquine|2,Coartem |3, Albendazo...",NaN,NaN,NaN,NaN,[dsc_rx]='1',NaN,NaN
310,dsc_rx_other2 --> dsc_rx3,discharge_information,NaN,text --> dropdown,Discharge treatment_other2 --> Discharge treat...,"nan --> 1, Amodiaquine|2,Coartem |3, Albendazo...",NaN,NaN,NaN,NaN,[dsc_rx]='1',NaN,NaN

In [541]:
df1.columns

Index(['Variable / Field Name', 'Form Name', 'Section Header', 'Field Type',
       'Field Label', 'Choices, Calculations, OR Slider Labels', 'Field Note',
       'Text Validation Type OR Show Slider Number', 'Text Validation Min',
       'Text Validation Max', 'Identifier?',
       'Branching Logic (Show field only if...)', 'Required Field?',
       'Custom Alignment', 'Question Number (surveys only)',
       'Matrix Group Name', 'Matrix Ranking?', 'Field Annotation'],
      dtype='object')

In [543]:
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])\
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])
#df1[['Field Type','New_FieldType']]   = pd.DataFrame([ x.split('-->') for x in df1['Field Type'].tolist() ])

#df1

In [544]:

df1[['Section Header','New_Section Header']] =  df1['Section Header'].str.split('-->',expand=True)
df1[['Form Name','New_formName']] =  df1['Form Name'].str.split('-->',expand=True)
df1[['Variable / Field Name','New_fieldName']] =  df1['Variable / Field Name'].str.split('-->',expand=True)
df1[['Field Type','New_FieldType']] =  df1['Field Type'].str.split('-->',expand=True)
df1[['Field Label','New_FieldLabel']] = df1['Field Label'].str.split('-->',expand=True)
df1[['Choices, Calculations, OR Slider Labels','New_Choices, Calculations, OR Slider Labels']] = df1['Choices, Calculations, OR Slider Labels'].str.split('-->',expand=True)
df1[['Field Note','New_FieldNote']] =  df1['Field Note'].str.split('-->',expand=True)
df1[['Text Validation Type OR Show Slider Number','New_Text Validation Type OR Show Slider Number']] = df1['Text Validation Type OR Show Slider Number'].str.split('-->',expand=True)
df1[['Text Validation Min','New_Text Validation Min']] = df1['Text Validation Min'].str.split('-->',expand=True)
df1[['Text Validation Max','New_Text Validation Max']] =  df1['Text Validation Max'].str.split('-->',expand=True)
#df1[['Identifier?','New_Identifier?']] = df1['Identifier?'].astype(str).str.split('-->',expand=True)
df1[['Branching Logic (Show field only if...)','New_Branching Logic (Show field only if)']] =  df1['Branching Logic (Show field only if...)'].str.split('-->',expand=True)

df1[['Required Field?','New_Required Field?']] =  df1['Required Field?'].str.split('-->',expand=True)
df1[['Custom Alignment','New_Custom Alignment']] =  df1['Custom Alignment'].str.split('-->',expand=True)
#df1[['Question Number (surveys only)','New_Question Number (surveys only)']] =  df1['Question Number (surveys only)'].str.split('-->',expand=True)

#df1[['Matrix Group Name)','New_Matrix Group Name']] = df1['Matrix Group Name'].str.split('-->',expand=True)
#df1[['Matrix Ranking?','New_Matrix Ranking?']] = df1['Matrix Ranking?'].str.split('-->',expand=True)
#df1[['Field Annotation','New_Field Annotation']] = ddf1['Field Annotation'].str.split('-->',expand=True)

In [545]:
df1

,Variable / Field Name,Form Name,Section Header,Field Type,Field Label,"Choices, Calculations, OR Slider Labels",Field Note,Text Validation Type OR Show Slider Number,Text Validation Min,Text Validation Max,...,New_FieldType,New_FieldLabel,"New_Choices, Calculations, OR Slider Labels",New_FieldNote,New_Text Validation Type OR Show Slider Number,New_Text Validation Min,New_Text Validation Max,New_Branching Logic (Show field only if),New_Required Field?,New_Custom Alignment
0,id,biodata,NaN,text,Unique ID,NaN,Use format [hosp id][record id] - eg.5100001 f...,nan,nan,nan,...,None,None,NaN,None,integer,5100000.0,8000000.0,NaN,None,NaN
1,hosp_id,biodata,NaN,dropdown,Hospital ID,"51, Kiambu DH |52, Machakos |53, Mama Lucy Kay...",NaN,NaN,NaN,NaN,...,None,None,"51, Kiambu DH | 52, Machakos | 53, Mama Lucy ...",NaN,NaN,NaN,NaN,NaN,None,NaN
2,depid,biodata,NaN,text,Data Entry Person ID,NaN,Eg. 02,NaN,NaN,NaN,...,None,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
3,date_today,biodata,NaN,text,Today's Date,NaN,NaN,date_dmy,NaN,NaN,...,None,None,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN
4,ipno,biodata,NaN,text,Patients IPNO,NaN,input -1 for empty,NaN,NaN,NaN,...,None,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN
5,age_years,biodata,NaN,text,Age (years),NaN,input -1 for empty,number,NaN,NaN,...,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN
6,age_mths,biodata,NaN,text,Age (months),NaN,input -1 for empty,number,NaN,NaN,...,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN
7,age_less1mnth,biodata,NaN,yesno,Age less than 1 month,NaN,NaN,NaN,NaN,NaN,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
8,age_days,biodata,NaN,text,Age (Days),NaN,input -1 for empty,number,NaN,NaN,...,None,None,NaN,None,None,NaN,NaN,None,NaN,NaN
9,date_adm,biodata,NaN,text,Admission Date,NaN,(For Empty Date type 01/01/1912),date_dmy,NaN,NaN,...,None,Residence - Location,NaN,Input -1 for empty,nan,NaN,NaN,NaN,NaN,NaN
10,ref_hosp,biodata,NaN,radio,Referred to hospital?,"1,Yes |0, No| -1, Empty",nan,NaN,NaN,NaN,...,text,Residence - District,nan,Input -1 for empty,NaN,NaN,NaN,NaN,nan,nan
11,ref_hosp_spec,biodata,NaN,text,Referred from which facility?,NaN,nan,nan,NaN,NaN,...,None,Admission Date,NaN,(For Empty Date type 01/01/1913),date_dmy,NaN,NaN,nan,nan,nan
12,readm_hosp,biodata,NaN,radio,Re-admission to this hospital?,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,...,None,Referred to hospital?,None,NaN,NaN,NaN,NaN,NaN,y,RH
13,weight,biodata,NaN,text,Weight (kgs),NaN,kgs ( enter -1 if not recorded),number,3.0,30.0,...,None,Referred from which facility?,NaN,nan,nan,nan,nan,[ref_hosp] = '1',None,RH
14,height,biodata,NaN,text,Height / Length (cm),nan,cm; ( enter -1 if not recorded),number,20.0,120.0,...,radio,Re-admission to this hospital?,"1,Yes |0, No| -1, Empty",nan,nan,nan,nan,NaN,nan,NaN
15,whz,biodata,NaN,dropdown,Weight-Height Z score,"1, 3SD | 2, 2SD | 3, 1SD | 4, 0SD | 5, -1SD | ...",nan,nan,nan,nan,...,text,Weight (kgs),nan,kgs ( enter -1 if not recorded),number,3.0,30.0,NaN,y,NaN
16,muac,biodata,NaN,text,MUAC (Mid-upper arm circumference) in cm,NaN,(enter -1 if not recorded),number,nan,nan,...,None,Height / Length (cm),NaN,cm; ( enter -1 if not recorded),None,20.0,120.0,NaN,nan,NaN
17,child_sex,biodata,NaN,radio,Gender,"0, Female | 1, Male | -1, Empty",NaN,NaN,NaN,NaN,...,dropdown,Weight-Height Z score,"1, 3SD | 2, 2SD | 3, 1SD | 4, 0SD | 5, -1SD |...",NaN,NaN,NaN,NaN,NaN,NaN,nan
18,vacc_source,biodata,NaN,radio,Vaccination data source,"1, PAR | 2, Free text",nan,nan,NaN,NaN,...,text,MUAC (Mid-upper arm circumference) in cm,nan,(enter -1 if not recorded),number,NaN,NaN,NaN,y,NaN
19,vacc_status_text,biodata,NaN,dropdown,Vaccination status from text,"1, Vaccination upto date for age(or as per KEP...",NaN,NaN,NaN,NaN,...,radio,Gender,"0, Female | 1, Male | -1, Empty",NaN,NaN,NaN,NaN,nan,NaN,RH
20,vacc_opv_penta,biodata,NaN,radio,Number of doses of OPV/Penta,"0, 0| 1,1|2,2| 3,3|-1, Empty",NaN,NaN,NaN,NaN,...,None,Vaccination data source,"1, PAR | 2, Free text | -1, Empty",NaN,NaN,NaN,NaN,nan,NaN,nan
21,pcv10,biodata,NaN,radio,Number of doses of PCV 10 (Pneumococcal vaccine),"0, 0| 1,1|2,2| 3,3|-1, Empty",NaN,NaN,NaN,NaN,...,dropdown,Vaccination status from text,"1, Vaccination upto date for age(or as per KE...",NaN,NaN,NaN,NaN,[vacc_source]='2',NaN,nan
22,rotavirus,biodata,NaN,radio,Number of doses of Rota virus given,"0, 0| 1,1|2,2| 3,3|-1, Empty",NaN,NaN,NaN,NaN,...,None,Number of doses of OPV/Penta,None,NaN,NaN,NaN,NaN,None,NaN,None
23,bcg,biodata,NaN,radio,BCG given,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,...,None,Number of doses of PCV 10 (Pneumococcal vaccine),"0, 0| 1,1|2,2| 3,3|-1, Empty",NaN,NaN,NaN,NaN,None,NaN,None
24,measles,biodata,NaN,radio,Measles given,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,...,None,Number of doses of Rota virus given,"0, 0| 1,1|2,2| 3,3|-1, Empty",NaN,NaN,NaN,NaN,[vacc_source] = '1' and [hosp_id] = '53' and ...,NaN,None
25,par,biodata,NaN,yesno,PAR used,nan,NaN,NaN,NaN,NaN,...,radio,BCG given,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,[vacc_source]='1',NaN,None
26,lo_illness_,history,<h1><font color=blue>HISTORY</font></h1>,text,Length of illness (days),nan,indicate the duration for longest presenting c...,number,NaN,21.0,...,radio,Measles given,"1,Yes |0, No| -1, Empty",nan,nan,NaN,nan,[vacc_source]='1',nan,RH
27,fever,history,NaN,radio,Fever,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,...,yesno,PAR used,nan,NaN,NaN,NaN,NaN,NaN,nan,None
28,fever_dur,history,nan,text,Fever duration,NaN,indicate in days,number,NaN,nan,...,None,Length of illness (days),NaN,indicate the duration for longest presenting ...,None,NaN,21.0,nan,y,NaN
29,cough,history,NaN,radio,Cough,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,...,None,Fever,None,NaN,NaN,NaN,NaN,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,dsc_dx1_malnutr,discharge_information,NaN,dropdown,Malnutrition,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwas...",NaN,NaN,NaN,NaN,...,None,Pneumonia,"1,Very Severe | 2, Severe |3, Non Severe |4,N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,dsc_dx1_anaemia,discharge_information,NaN,dropdown,Anaemia,"1, Severe|2, Non Severe | 3, No classification",NaN,NaN,NaN,NaN,...,None,Diarrhoea / Acute GE (Gastro-Enteritis),"1,Non-bloody | 2, bloody | 3, No classification",NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,dsc_dx1_meningitis,discharge_information,NaN,yesno,Meningitis,nan,NaN,NaN,NaN,NaN,...,dropdown,Dehydration,"1,Shock |2, Severe | 3, Some|4, No Classifica...",NaN,NaN,NaN,NaN,NaN,NaN,nan
284,dsc_dx1_asthma,discharge_information,NaN,dropdown,Asthma,"1,Very Severe | 2, Severe |3, Non Severe (mild...",NaN,NaN,NaN,NaN,...,None,HIV / AIDS,"1,Known | 2, Possible",NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,dsc_dx1_tb,discharge_information,NaN,dropdown,TB,"1, PTB | 2, Extra-Pulmonary",NaN,NaN,NaN,NaN,...,None,Malnutrition,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwa...",NaN,NaN,NaN,NaN,NaN,NaN,nan
286,dsc_dx1_other_1,discharge_information,NaN,dropdown,Other Primary discharge diagnoses 1,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,...,None,Anaemia,"1, Severe|2, Non Severe | 3, No classification",NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,dsc_dx1_other_2,discharge_information,NaN,text,Other Primary discharge diagnoses 2,NaN,NaN,NaN,NaN,NaN,...,yesno,Meningitis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RH
288,dsc_dx2,discharge_information,Secondary diagnosis (Enter all other diagnosis),yesno,Is there a secondary diagnosis?,nan,NaN,NaN,NaN,NaN,...,dropdown,Asthma,"1,Very Severe | 2, Severe |3, Non Severe (mil...",NaN,NaN,NaN,NaN,NaN,NaN,nan
289,dsc_dx2_malaria,discharge_information,NaN,dropdown,Malaria,"1,Severe | 2, Non severe |3, Non Classified",NaN,NaN,NaN,NaN,...,None,TB,"1, PTB | 2, Extra-Pulmonary",NaN,NaN,NaN,NaN,nan,NaN,RH
290,dsc_dx2_pneum,discharge_information,NaN,dropdown,Pneumonia,"1,Very Severe | 2, Severe |3, Non Severe |4,No...",NaN,NaN,NaN,NaN,...,None,Other Primary discharge diagnoses 1,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4,...",NaN,NaN,NaN,NaN,nan,NaN,NaN
291,dsc_dx2_diarrhoea,discharge_information,NaN,dropdown,Diarrhoea / Acute GE (Gastro-Enteritis),"1,Non-bloody | 2, bloody | 3, No classification",NaN,NaN,NaN,NaN,...,text,Other Primary discharge diagnoses 2,nan,NaN,NaN,NaN,NaN,nan,NaN,NaN
292,dsc_dx2_dehydrat,discharge_information,nan,dropdown,Dehydration,"1,Shock |2, Severe | 3, Some|4, No Classificat...",NaN,NaN,NaN,NaN,...,yesno,Is there a secondary diagnosis?,nan,NaN,NaN,NaN,NaN,nan,NaN,RH
293,dsc_dx2_hiv,discharge_information,NaN,dropdown,HIV / AIDS,"1,Known | 2, Possible",NaN,NaN,NaN,NaN,...,None,Malaria,"1,Severe | 2, Non severe |3, Non Classified",NaN,NaN,NaN,NaN,None,NaN,NaN
294,dsc_dx2_malnutr,discharge_information,NaN,dropdown,Malnutrition,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwas...",NaN,NaN,NaN,NaN,...,None,Pneumonia,"1,Very Severe | 2, Severe |3, Non Severe |4,N...",NaN,NaN,NaN,NaN,None,NaN,NaN
295,dsc_dx2_anaemia,discharge_information,NaN,dropdown,Anaemia,"1, Severe|2, Non Severe | 3, No classification",NaN,NaN,NaN,NaN,...,None,Diarrhoea / Acute GE (Gastro-Enteritis),"1,Non-bloody | 2, bloody | 3, No classification",NaN,NaN,NaN,NaN,None,NaN,NaN
296,dsc_dx2_meningitis,discharge_information,NaN,yesno,Meningitis,nan,NaN,NaN,NaN,NaN,...,dropdown,Dehydration,"1,Shock |2, Severe | 3, Some|4, No Classifica...",NaN,NaN,NaN,NaN,None,NaN,nan
297,dsc_dx2_asthma,discharge_information,NaN,dropdown,Asthma,"1,Very Severe | 2, Severe |3, Non Severe (mild...",NaN,NaN,NaN,NaN,...,None,HIV / AIDS,"1,Known | 2, Possible",NaN,NaN,NaN,NaN,None,NaN,NaN
298,dsc_dx2_tb,discharge_information,NaN,dropdown,TB,"1, PTB | 2, Extra-Pulmonary",NaN,NaN,NaN,NaN,...,None,Malnutrition,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwa...",NaN,NaN,NaN,NaN,None,NaN,nan
299,dsc_dx2_other_1,discharge_information,NaN,dropdown,Other secondary discharge diagnoses 1,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,...,None,Anaemia,"1, Severe|2, Non Severe | 3, No classification",NaN,NaN,NaN,NaN,None,NaN,NaN
300,dsc_dx2_other_2,discharge_information,NaN,dropdown,Other secondary discharge diagnoses 2,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,...,yesno,Meningitis,nan,NaN,NaN,NaN,NaN,None,NaN,RH
301,dsc_dx2_other_3,discharge_information,NaN,text,Other secondary discharge diagnoses 3,nan,NaN,NaN,NaN,NaN,...,dropdown,Asthma,"1,Very Severe | 2, Severe |3, Non Severe (mil...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN
302,dsc_dx2_other_4,discharge_information,NaN,text,Other secondary discharge diagnoses 4,nan,NaN,NaN,NaN,NaN,...,dropdown,TB,"1, PTB | 2, Extra-Pulmonary",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH
303,dsc_rx,discharge_information,Discharge treatment,yesno,Discharge treatment prescribed,nan,NaN,NaN,NaN,NaN,...,dropdown,Other secondary discharge diagnoses 1,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4,...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,nan
304,dsc_rx1,discharge_information,NaN,dropdown,Discharge treatment1,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,...,None,Other secondary discharge diagnoses 2,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4,...",NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN
305,dsc_rx2,discharge_information,NaN,dropdown,Discharge treatment2,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,...,text,Other secondary discharge diagnoses 3,nan,NaN,NaN,NaN,NaN,nan,NaN,NaN
306,dsc_rx3,discharge_information,NaN,dropdown,Discharge treatment3,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,...,text,Other secondary discharge diagnoses 4,nan,NaN,NaN,NaN,NaN,nan,NaN,NaN
307,dsc_rx4,discharge_information,nan,dropdown,Discharge treatment4,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,...,yesno,Discharge treatment prescribed,nan,NaN,NaN,NaN,NaN,nan,NaN,RH
308,dsc_rx5,discharge_information,NaN,dropdown,Discharge treatment5,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,...,None,Discharge treatment1,None,NaN,NaN,NaN,NaN,None,NaN,NaN
309,dsc_rx_other1,discharge_information,NaN,text,Discharge treatment_other1,nan,NaN,NaN,NaN,NaN,...,dropdown,Discharge treatment2,"1, Amodiaquine|2,Coartem |3, Albendazole | 4,...",NaN,NaN,NaN,NaN,None,NaN,NaN
310,dsc_rx_other2,discharge_information,NaN,text,Discharge treatment_other2,nan,NaN,NaN,NaN,NaN,...,dropdown,Discharge treatment3,"1, Amodiaquine|2,Coartem |3, Albendazole | 4,...",NaN,NaN,NaN,NaN,None,NaN,NaN

In [546]:
df1.to_csv("Differeb.csv", index=False)

In [547]:
df1['Form Name'] == df1['New_FieldNote']

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
281    False
282    False
283    False
284    False
285    False
286    False
287    False
288    False
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299    False
300    False
301    False
302    False
303    False
304    False
305    False
306    False
307    False
308    False
309    False
310    False
Length: 311, dtype: bool

In [497]:
#df = df1.reindex('Variable / Field Name', 'Form Name', 'Section Header', 'Field Type',
       #'Field Label', 'Choices, Calculations, OR Slider Labels', 'Field Note',
       #'Text Validation Type OR Show Slider Number', 'Text Validation Min',
       #'Text Validation Max', 'Identifier?',
       #'Branching Logic (Show field only if...)', 'Required Field?',
      # 'Custom Alignment', 'Question Number (surveys only)',
       #'Matrix Group Name', 'Matrix Ranking?', 'Field Annotation',
        'New_fieldName','New_formName','New_Section Header',
               # 'New_FieldType','New_FieldLabel', 'New_Choices, Calculations, OR Slider Labels',
       #'New_FieldNote', 'New_Text Validation Type OR Show Slider Number',
       #'New_Text Validation Min', 'New_Text Validation Max',
       #'New_Branching Logic (Show field only if)', 'New_Required Field?',
       #'New_Custom Alignment', axis=1)

In [ ]:
dfo=dff.reindex(['Variable / Field Name','New_fieldName', 'Form Name', 'New_formName','Section Header', 'New_Section Header',
                 'Field Type', 'New_FieldType', 'Field Label', 'New_FieldLabel', 'Choices, Calculations, OR Slider Labels', 
                 'New_Choices, Calculations, OR Slider Labels', 'Field Note', 'New_FieldNote','Text Validation Type OR Show Slider Number',
                 'New_Text Validation Type OR Show Slider Number',
                 'Wavenumber_one', 'Wavenumber_last', 'Min_absorbance', 'Max_Absorbance'], axis=1)

In [185]:
df1['Field Label', 'New_FieldLabel'] = df1['Field Label'].str.split('-->').str[1]

df1['Text Validation Min','New_Text Validation Min']= df1['Text Validation Min'].str.split('-->').str[1]
df1['Section Header','New_Section Header'] = df1['Section Header'].str.split('-->').str[1]
df1['Form Name','New_formName'] = df1['Form Name'].str.split('-->').str[1]
df1['Variable / Field Name','New_fieldName'] = df1['Variable / Field Name'].str.split('-->').str[1]
df1['Field Type','New_FieldType'] = df1['Field Type'].str.split('-->').str[1]
df1['Field Label','New_FieldLabel'] = df1['Field Label'].str.split('-->').str[1]
df1['Choices, Calculations, OR Slider Labels','New_Choices, Calculations, OR Slider Labels'] = df1['Choices, Calculations, OR Slider Labels'].str.split('-->').str[1]
df1[['Field Note','New_FieldNote']] = df1['Field Note'].str.split('-->',expand=True)

df1['Text Validation Type OR Show Slider Number','New_Text Validation Type OR Show Slider Number'] = df1['Text Validation Type OR Show Slider Number'].str.split('-->').str[1]

df1['Text Validation Max','New_Text Validation Max'] = df1['Text Validation Max'].str.split('-->').str[1]
df1['Identifier?','New_Identifier?'] = df1['Identifier?'].str.split('-->').str[1]
df1['Branching Logic (Show field only if...)','New_Branching Logic (Show field only if)'] = df1['Branching Logic (Show field only if...)'].str.split('-->').str[1]
df1['Required Field?','New_Required Field?'] = df1['Required Field?'].str.split('-->').str[1]
df1['Custom Alignment','New_Custom Alignment'] = df1['Custom Alignment'].str.split('-->').str[1]
#df1['Question Number (surveys only)','New_Question Number (surveys only)'] = df1['Question Number (surveys only)'].str.split('-->').str[1]

#df1['Matrix Group Name)','New_Matrix Group Name'] =df1['Matrix Group Name'].str.split('-->').str[1]
#df1['Matrix Ranking?','New_Matrix Ranking?'] = df1['Matrix Ranking?'].str.split('-->').str[1]
#df1['Field Annotation','New_Field Annotation'] = df1['Field Annotation'].str.split('-->').str[1]

AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas

In [104]:
df1

,Variable / Field Name,Form Name,Section Header,Field Type,Field Label,"Choices, Calculations, OR Slider Labels",Field Note,Text Validation Type OR Show Slider Number,Text Validation Min,Text Validation Max,...,Matrix Ranking?,Field Annotation,"(Field Label, New_FieldLabel)","(Text Validation Min, New_Text Validation Min)","(Section Header, New_Section Header)","(Form Name, New_formName)","(Variable / Field Name, New_fieldName)","(Field Type, New_FieldType)","(Choices, Calculations, OR Slider Labels, New_Choices, Calculations, OR Slider Labels)",New_FieldNote
0,id,biodata,NaN,text,Unique ID,NaN,Use format [hosp id][record id] - eg.5100001 f...,nan --> integer,nan --> 5100000.0,nan --> 8000000.0,...,NaN,NaN,NaN,5100000.0,NaN,NaN,NaN,NaN,NaN,None
1,hosp_id,biodata,NaN,dropdown,Hospital ID,"51, Kiambu DH |52, Machakos |53, Mama Lucy Kay...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"51, Kiambu DH | 52, Machakos | 53, Mama Lucy ...",NaN
2,depid,biodata,NaN,text,Data Entry Person ID,NaN,Eg. 02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,date_today,biodata,NaN,text,Today's Date,NaN,NaN,date_dmy,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ipno,biodata,NaN,text,Patients IPNO,NaN,input -1 for empty,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
5,age_years,biodata,NaN,text,Age (years),NaN,input -1 for empty,number,0,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
6,age_mths,biodata,NaN,text,Age (months),NaN,input -1 for empty,number,2,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
7,age_less1mnth,biodata,NaN,yesno,Age less than 1 month,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,age_days,biodata,NaN,text,Age (Days),NaN,input -1 for empty,number,0,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
9,date_adm --> res_loc,biodata,NaN,text,Admission Date --> Residence - Location,NaN,(For Empty Date type 01/01/1912),date_dmy --> nan,NaN,NaN,...,NaN,NaN,Residence - Location,NaN,NaN,NaN,res_loc,NaN,NaN,Input -1 for empty
10,ref_hosp --> res_dst,biodata,NaN,radio --> text,Referred to hospital? --> Residence - District,"1,Yes |0, No| -1, Empty --> nan",nan,NaN,NaN,NaN,...,NaN,NaN,Residence - District,NaN,NaN,NaN,res_dst,text,nan,Input -1 for empty
11,ref_hosp_spec --> date_adm,biodata,NaN,text,Referred from which facility? --> Admission Date,NaN,nan,nan --> date_dmy,NaN,NaN,...,NaN,NaN,Admission Date,NaN,NaN,NaN,date_adm,NaN,NaN,(For Empty Date type 01/01/1913)
12,readm_hosp --> ref_hosp,biodata,NaN,radio,Re-admission to this hospital? --> Referred to...,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,...,NaN,NaN,Referred to hospital?,NaN,NaN,NaN,ref_hosp,NaN,NaN,NaN
13,weight --> ref_hosp_spec,biodata,NaN,text,Weight (kgs) --> Referred from which facility?,NaN,kgs ( enter -1 if not recorded),number --> nan,3.0 --> nan,30.0 --> nan,...,NaN,NaN,Referred from which facility?,nan,NaN,NaN,ref_hosp_spec,NaN,NaN,nan
14,height --> readm_hosp,biodata,NaN,text --> radio,Height / Length (cm) --> Re-admission to this ...,"nan --> 1,Yes |0, No| -1, Empty",cm; ( enter -1 if not recorded),number --> nan,20.0 --> nan,120.0 --> nan,...,NaN,NaN,Re-admission to this hospital?,nan,NaN,NaN,readm_hosp,radio,"1,Yes |0, No| -1, Empty",nan
15,whz --> weight,biodata,NaN,dropdown --> text,Weight-Height Z score --> Weight (kgs),"1, 3SD | 2, 2SD | 3, 1SD | 4, 0SD | 5, -1SD | ...",nan,nan --> number,nan --> 3.0,nan --> 30.0,...,NaN,NaN,Weight (kgs),3.0,NaN,NaN,weight,text,nan,kgs ( enter -1 if not recorded)
16,muac --> height,biodata,NaN,text,MUAC (Mid-upper arm circumference) in cm --> H...,NaN,(enter -1 if not recorded),number,nan --> 20.0,nan --> 120.0,...,NaN,NaN,Height / Length (cm),20.0,NaN,NaN,height,NaN,NaN,cm; ( enter -1 if not recorded)
17,child_sex --> whz,biodata,NaN,radio --> dropdown,Gender --> Weight-Height Z score,"0, Female | 1, Male | -1, Empty --> 1, 3SD | 2...",NaN,NaN,NaN,NaN,...,NaN,NaN,Weight-Height Z score,NaN,NaN,NaN,whz,dropdown,"1, 3SD | 2, 2SD | 3, 1SD | 4, 0SD | 5, -1SD |...",NaN
18,vacc_source --> muac,biodata,NaN,radio --> text,Vaccination data source --> MUAC (Mid-upper ar...,"1, PAR | 2, Free text --> nan",nan,nan --> number,NaN,NaN,...,NaN,NaN,MUAC (Mid-upper arm circumference) in cm,NaN,NaN,NaN,muac,text,nan,(enter -1 if not recorded)
19,vacc_status_text --> child_sex,biodata,NaN,dropdown --> radio,Vaccination status from text --> Gender,"1, Vaccination upto date for age(or as per KEP...",NaN,NaN,NaN,NaN,...,NaN,NaN,Gender,NaN,NaN,NaN,child_sex,radio,"0, Female | 1, Male | -1, Empty",NaN
20,vacc_opv_penta --> vacc_source,biodata,NaN,radio,Number of doses of OPV/Penta --> Vaccination ...,"0, 0| 1,1|2,2| 3,3|-1, Empty --> 1, PAR | 2, F...",NaN,NaN,NaN,NaN,...,NaN,NaN,Vaccination data source,NaN,NaN,NaN,vacc_source,NaN,"1, PAR | 2, Free text | -1, Empty",NaN
21,pcv10 --> vacc_status_text,biodata,NaN,radio --> dropdown,Number of doses of PCV 10 (Pneumococcal vaccin...,"0, 0| 1,1|2,2| 3,3|-1, Empty --> 1, Vaccinatio...",NaN,NaN,NaN,NaN,...,NaN,NaN,Vaccination status from text,NaN,NaN,NaN,vacc_status_text,dropdown,"1, Vaccination upto date for age(or as per KE...",NaN
22,rotavirus --> vacc_opv_penta,biodata,NaN,radio,Number of doses of Rota virus given --> Number...,"0, 0| 1,1|2,2| 3,3|-1, Empty",NaN,NaN,NaN,NaN,...,NaN,NaN,Number of doses of OPV/Penta,NaN,NaN,NaN,vacc_opv_penta,NaN,NaN,NaN
23,bcg --> pcv10,biodata,NaN,radio,BCG given --> Number of doses of PCV 10 (Pneum...,"1,Yes |0, No| -1, Empty --> 0, 0| 1,1|2,2| 3,...",NaN,NaN,NaN,NaN,...,NaN,NaN,Number of doses of PCV 10 (Pneumococcal vaccine),NaN,NaN,NaN,pcv10,NaN,"0, 0| 1,1|2,2| 3,3|-1, Empty",NaN
24,measles --> rotavirus,biodata,NaN,radio,Measles given --> Number of doses of Rota viru...,"1,Yes |0, No| -1, Empty --> 0, 0| 1,1|2,2| 3,...",NaN,NaN,NaN,NaN,...,NaN,NaN,Number of doses of Rota virus given,NaN,NaN,NaN,rotavirus,NaN,"0, 0| 1,1|2,2| 3,3|-1, Empty",NaN
25,par --> bcg,biodata,NaN,yesno --> radio,PAR used --> BCG given,"nan --> 1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,...,NaN,NaN,BCG given,NaN,NaN,NaN,bcg,radio,"1,Yes |0, No| -1, Empty",NaN
26,lo_illness_ --> measles,history --> biodata,<h1><font color=blue>HISTORY</font></h1> --> nan,text --> radio,Length of illness (days) --> Measles given,"nan --> 1,Yes |0, No| -1, Empty",indicate the duration for longest presenting c...,number --> nan,0,21.0 --> nan,...,NaN,NaN,Measles given,NaN,nan,biodata,measles,radio,"1,Yes |0, No| -1, Empty",nan
27,fever --> par,history --> biodata,NaN,radio --> yesno,Fever --> PAR used,"1,Yes |0, No| -1, Empty --> nan",NaN,NaN,NaN,NaN,...,NaN,NaN,PAR used,NaN,NaN,biodata,par,yesno,nan,NaN
28,fever_dur --> lo_illness_,history,nan --> <h1><font color=blue>HISTORY</font></h1>,text,Fever duration --> Length of illness (days),NaN,indicate in days,number,NaN,nan --> 21.0,...,NaN,NaN,Length of illness (days),NaN,<h1><font color=blue>HISTORY</font></h1>,NaN,lo_illness_,NaN,NaN,indicate the duration for longest presenting ...
29,cough --> fever,history,NaN,radio,Cough --> Fever,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,...,NaN,NaN,Fever,NaN,NaN,NaN,fever,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,dsc_dx1_malnutr --> dsc_dx1_pneum,discharge_information,NaN,dropdown,Malnutrition --> Pneumonia,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwas...",NaN,NaN,NaN,NaN,...,NaN,NaN,Pneumonia,NaN,NaN,NaN,dsc_dx1_pneum,NaN,"1,Very Severe | 2, Severe |3, Non Severe |4,N...",NaN
282,dsc_dx1_anaemia --> dsc_dx1_diarrhoea,discharge_information,NaN,dropdown,Anaemia --> Diarrhoea / Acute GE (Gastro-Enter...,"1, Severe|2, Non Severe | 3, No classification...",NaN,NaN,NaN,NaN,...,NaN,NaN,Diarrhoea / Acute GE (Gastro-Enteritis),NaN,NaN,NaN,dsc_dx1_diarrhoea,NaN,"1,Non-bloody | 2, bloody | 3, No classification",NaN
283,dsc_dx1_meningitis --> dsc_dx1_dehydrat,discharge_information,NaN,yesno --> dropdown,Meningitis --> Dehydration,"nan --> 1,Shock |2, Severe | 3, Some|4, No Cla...",NaN,NaN,NaN,NaN,...,NaN,NaN,Dehydration,NaN,NaN,NaN,dsc_dx1_dehydrat,dropdown,"1,Shock |2, Severe | 3, Some|4, No Classifica...",NaN
284,dsc_dx1_asthma --> dsc_dx1_hiv,discharge_information,NaN,dropdown,Asthma --> HIV / AIDS,"1,Very Severe | 2, Severe |3, Non Severe (mild...",NaN,NaN,NaN,NaN,...,NaN,NaN,HIV / AIDS,NaN,NaN,NaN,dsc_dx1_hiv,NaN,"1,Known | 2, Possible",NaN
285,dsc_dx1_tb --> dsc_dx1_malnutr,discharge_information,NaN,dropdown,TB --> Malnutrition,"1, PTB | 2, Extra-Pulmonary --> 1,Kwashiorkor ...",NaN,NaN,NaN,NaN,...,NaN,NaN,Malnutrition,NaN,NaN,NaN,dsc_dx1_malnutr,NaN,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwa...",NaN
286,dsc_dx1_other_1 --> dsc_dx1_anaemia,discharge_information,NaN,dropdown,Other Primary discharge diagnoses 1 --> Anaemia,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,...,NaN,NaN,Anaemia,NaN,NaN,NaN,dsc_dx1_anaemia,NaN,"1, Severe|2, Non Severe | 3, No classification",NaN
287,dsc_dx1_other_2 --> dsc_dx1_meningitis,discharge_information,NaN,text --> yesno,Other Primary discharge diagnoses 2 --> Menin...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Meningitis,NaN,NaN,NaN,dsc_dx1_meningitis,yesno,NaN,NaN
288,dsc_dx2 --> dsc_dx1_asthma,discharge_information,Secondary diagnosis (Enter all other diagnosis...,yesno --> dropdown,Is there a secondary diagnosis? --> Asthma,"nan --> 1,Very Severe | 2, Severe |3, Non Seve...",NaN,NaN,NaN,NaN,...,NaN,NaN,Asthma,NaN,nan,NaN,dsc_dx1_asthma,dropdown,"1,Very Severe | 2, Severe |3, Non Severe (mil...",NaN
289,dsc_dx2_malaria --> dsc_dx1_tb,discharge_information,NaN,dropdown,Malaria --> TB,"1,Severe | 2, Non severe |3, Non Classified --...",NaN,NaN,NaN,NaN,...,NaN,NaN,TB,NaN,NaN,NaN,dsc_dx1_tb,NaN,"1, PTB | 2, Extra-Pulmonary",NaN
290,dsc_dx2_pneum --> dsc_dx1_other_1,discharge_information,NaN,dropdown,Pneumonia --> Other Primary discharge diagnose...,"1,Very Severe | 2, Severe |3, Non Severe |4,No...",NaN,NaN,NaN,NaN,...,NaN,NaN,Other Primary discharge diagnoses 1,NaN,NaN,NaN,dsc_dx1_other_1,NaN,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4,...",NaN
291,dsc_dx2_diarrhoea --> dsc_dx1_other_2,discharge_information,NaN,dropdown --> text,Diarrhoea / Acute GE (Gastro-Enteritis) --> Ot...,"1,Non-bloody | 2, bloody | 3, No classificatio...",NaN,NaN,NaN,NaN,...,NaN,NaN,Other Primary discharge diagnoses 2,NaN,NaN,NaN,dsc_dx1_other_2,text,nan,NaN
292,dsc_dx2_dehydrat --> dsc_dx2,discharge_information,nan --> Secondary diagnosis (Enter all other d...,dropdown --> yesno,Dehydration --> Is there a secondary diagnosis?,"1,Shock |2, Severe | 3, Some|4, No Classificat...",NaN,NaN,NaN,NaN,...,NaN,NaN,Is there a secondary diagnosis?,NaN,Secondary diagnosis (Enter all other diagnosis),NaN,dsc_dx2,yesno,nan,NaN
293,dsc_dx2_hiv --> dsc_dx2_malaria,discharge_information,NaN,dropdown,HIV / AIDS --> Malaria,"1,Known | 2, Possible --> 1,Severe | 2, Non se...",NaN,NaN,NaN,NaN,...,NaN,NaN,Malaria,NaN,NaN,NaN,dsc_dx2_malaria,NaN,"1,Severe | 2, Non severe |3, Non Classified",NaN
294,dsc_dx2_malnutr --> dsc_dx2_pneum,discharge_information,NaN,dropdown,Malnutrition --> Pneumonia,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwas...",NaN,NaN,NaN,NaN,...,NaN,NaN,Pneumonia,NaN,NaN,NaN,dsc_dx2_pneum,NaN,"1,Very Severe | 2, Severe |3, Non Severe |4,N...",NaN
295,dsc_dx2_anaemia --> dsc_dx2_diarrhoea,discharge_information,NaN,dropdown,Anaemia --> Diarrhoea / Acute GE (Gastro-Enter...,"1, Severe|2, Non Severe | 3, No classification...",NaN,NaN,NaN,NaN,...,NaN,NaN,Diarrhoea / Acute GE (Gastro-Enteritis),NaN,NaN,NaN,dsc_dx2_diarrhoea,NaN,"1,Non-bloody | 2, bloody | 3, No classification",NaN
296,dsc_dx2_meningitis --> dsc_dx2_dehydrat,discharge_information,NaN,yesno --> dropdown,Meningitis --> Dehydration,"nan --> 1,Shock |2, Severe | 3, Some|4, No Cla...",NaN,NaN,NaN,NaN,...,NaN,NaN,Dehydration,NaN,NaN,NaN,dsc_dx2_dehydrat,dropdown,"1,Shock |2, Severe | 3, Some|4, No Classifica...",NaN
297,dsc_dx2_asthma --> dsc_dx2_hiv,discharge_information,NaN,dropdown,Asthma --> HIV / AIDS,"1,Very Severe | 2, Severe |3, Non Severe (mild...",NaN,NaN,NaN,NaN,...,NaN,NaN,HIV / AIDS,NaN,NaN,NaN,dsc_dx2_hiv,NaN,"1,Known | 2, Possible",NaN
298,dsc_dx2_tb --> dsc_dx2_malnutr,discharge_information,NaN,dropdown,TB --> Malnutrition,"1, PTB | 2, Extra-Pulmonary --> 1,Kwashiorkor ...",NaN,NaN,NaN,NaN,...,NaN,NaN,Malnutrition,NaN,NaN,NaN,dsc_dx2_malnutr,NaN,"1,Kwashiorkor | 2, Marasmus | 3, Marasmus-Kwa...",NaN
299,dsc_dx2_other_1 --> dsc_dx2_anaemia,discharge_information,NaN,dropdown,Other secondary discharge diagnoses 1 --> Ana...,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,...,NaN,NaN,Anaemia,NaN,NaN,NaN,dsc_dx2_anaemia,NaN,"1, Severe|2, Non Severe | 3, No classification",NaN
300,dsc_dx2_other_2 --> dsc_dx2_meningitis,discharge_information,NaN,dropdown --> yesno,Other secondary discharge diagnoses 2 --> Men...,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4, ...",NaN,NaN,NaN,NaN,...,NaN,NaN,Meningitis,NaN,NaN,NaN,dsc_dx2_meningitis,yesno,nan,NaN
301,dsc_dx2_other_3 --> dsc_dx2_asthma,discharge_information,NaN,text --> dropdown,Other secondary discharge diagnoses 3 --> Asthma,"nan --> 1,Very Severe | 2, Severe |3, Non Seve...",NaN,NaN,NaN,NaN,...,NaN,NaN,Asthma,NaN,NaN,NaN,dsc_dx2_asthma,dropdown,"1,Very Severe | 2, Severe |3, Non Severe (mil...",NaN
302,dsc_dx2_other_4 --> dsc_dx2_tb,discharge_information,NaN,text --> dropdown,Other secondary discharge diagnoses 4 --> TB,"nan --> 1, PTB | 2, Extra-Pulmonary",NaN,NaN,NaN,NaN,...,NaN,NaN,TB,NaN,NaN,NaN,dsc_dx2_tb,dropdown,"1, PTB | 2, Extra-Pulmonary",NaN
303,dsc_rx --> dsc_dx2_other_1,discharge_information,Discharge treatment --> nan,yesno --> dropdown,Discharge treatment prescribed --> Other secon...,"nan --> 2, ACUTE ABDOMEN | 3, Adenoid Hypentro...",NaN,NaN,NaN,NaN,...,NaN,NaN,Other secondary discharge diagnoses 1,NaN,nan,NaN,dsc_dx2_other_1,dropdown,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4,...",NaN
304,dsc_rx1 --> dsc_dx2_other_2,discharge_information,NaN,dropdown,Discharge treatment1 --> Other secondary disch...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,...,NaN,NaN,Other secondary discharge diagnoses 2,NaN,NaN,NaN,dsc_dx2_other_2,NaN,"2, ACUTE ABDOMEN | 3, Adenoid Hypentropy | 4,...",NaN
305,dsc_rx2 --> dsc_dx2_other_3,discharge_information,NaN,dropdown --> text,Discharge treatment2 --> Other secondary disc...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,...,NaN,NaN,Other secondary discharge diagnoses 3,NaN,NaN,NaN,dsc_dx2_other_3,text,nan,NaN
306,dsc_rx3 --> dsc_dx2_other_4,discharge_information,NaN,dropdown --> text,Discharge treatment3 --> Other secondary disc...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,...,NaN,NaN,Other secondary discharge diagnoses 4,NaN,NaN,NaN,dsc_dx2_other_4,text,nan,NaN
307,dsc_rx4 --> dsc_rx,discharge_information,nan --> Discharge treatment,dropdown --> yesno,Discharge treatment4 --> Discharge treatment p...,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,...,NaN,NaN,Discharge treatment prescribed,NaN,Discharge treatment,NaN,dsc_rx,yesno,nan,NaN
308,dsc_rx5 --> dsc_rx1,discharge_information,NaN,dropdown,Discharge treatment5 --> Discharge treatment1,"1, Amodiaquine|2,Coartem |3, Albendazole | 4, ...",NaN,NaN,NaN,NaN,...,NaN,NaN,Discharge treatment1,NaN,NaN,NaN,dsc_rx1,NaN,NaN,NaN
309,dsc_rx_other1 --> dsc_rx2,discharge_information,NaN,text --> dropdown,Discharge treatment_other1 --> Discharge treat...,"nan --> 1, Amodiaquine|2,Coartem |3, Albendazo...",NaN,NaN,NaN,NaN,...,NaN,NaN,Discharge treatment2,NaN,NaN,NaN,dsc_rx2,dropdown,"1, Amodiaquine|2,Coartem |3, Albendazole | 4,...",NaN
310,dsc_rx_other2 --> dsc_rx3,discharge_information,NaN,text --> dropdown,Discharge treatment_other2 --> Discharge treat...,"nan --> 1, Amodiaquine|2,Coartem |3, Albendazo...",NaN,NaN,NaN,NaN,...,NaN,NaN,Discharge treatment3,NaN,NaN,NaN,dsc_rx3,dropdown,"1, Amodiaquine|2,Coartem |3, Albendazole | 4,...",NaN

In [12]:
df1['Section Header','New_Section Header'] = df1['Section Header'].str.split('-->').str[1]
df1['Form Name','New_formName'] = df1['Form Name'].str.split('-->').str[1]
df1['Variable / Field Name','New_fieldName'] = df1['Variable / Field Name'].str.split('-->').str[1]
df1['Field Type','New_FieldType'] = df1['Field Type'].str.split('-->').str[1]
df1['Field Label','New_FieldLabel'] = df1['Field Label'].str.split('-->').str[1]
df1['Choices, Calculations, OR Slider Labels','New_Choices, Calculations, OR Slider Labels'] = df1['Choices, Calculations, OR Slider Labels'].str.split('-->').str[1]
df1[['Field Note','New_FieldNote']] = df1['Field Note'].str.split('-->',expand=True)
df1['Text Validation Type OR Show Slider Number','New_Text Validation Type OR Show Slider Number'] = df1['Text Validation Type OR Show Slider Number'].str.split('-->').str[1]

df1['Text Validation Max','New_Text Validation Max'] = df1['Text Validation Max'].str.split('-->').str[1]
df1['Identifier?','New_Identifier?'] = df1['Identifier?'].str.split('-->').str[1]
df1['Branching Logic (Show field only if...)','New_Branching Logic (Show field only if)'] = df1['Branching Logic (Show field only if...)'].str.split('-->').str[1]

df1['Required Field?','New_Required Field?'] = df1['Required Field?'].str.split('-->').str[1]
df1['Custom Alignment','New_Custom Alignment'] = df1['Custom Alignment'].str.split('-->').str[1]
df1['Question Number (surveys only)','New_Question Number (surveys only)'] = df1['Question Number (surveys only)'].str.split('-->').str[1]

df1['Matrix Group Name)','New_Matrix Group Name'] =df1['Matrix Group Name'].str.split('-->').str[1]
df1['Matrix Ranking?','New_Matrix Ranking?'] = df1['Matrix Ranking?'].str.split('-->').str[1]
df1['Field Annotation','New_Field Annotation'] = df1['Field Annotation'].str.split('-->').str[1]

In [7]:
compare.matches(ignore_extra_columns=False)

False

In [13]:
# This method prints out a human-readable report summarizing and sampling differences
print(type(compare.report()))

<class 'str'>

In [9]:
import glob
import os
import pandas as pd

In [10]:
# the path to your csv file directory
mycsvdir = 'C:/Users/lmumelo/Downloads/Compare_obj/cin_dicts'

In [11]:
# get all the csv files in that directory (assuming they have the extension .csv)
csvfiles = glob.glob(os.path.join(mycsvdir, '*.csv'))

In [12]:
# loop through the files and read them in with pandas
dataframes = []  # a list to hold all the individual pandas DataFrames
for csvfile in csvfiles:
    df = pd.read_csv(csvfile)
    dataframes.append(df)

In [14]:
dataframes[1]

,Variable / Field Name,Form Name,Section Header,Field Type,Field Label,"Choices, Calculations, OR Slider Labels",Field Note,Text Validation Type OR Show Slider Number,Text Validation Min,Text Validation Max,Identifier?,Branching Logic (Show field only if...),Required Field?,Custom Alignment,Question Number (surveys only),Matrix Group Name,Matrix Ranking?,Field Annotation
0,id,biodata,NaN,text,Unique ID,NaN,Use format [hosp id][record id] - eg.5100001 f...,integer,5100000,8000000.0,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
1,doc_source,biodata,NaN,radio,Document Source?,"1, PAR | 2, NAR | 3, Neither PAR/NAR used",NaN,NaN,NaN,NaN,NaN,NaN,y,RH,NaN,NaN,NaN,NaN
2,surgical_burns,biodata,NaN,yesno,Surgical/Burns Patient?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,y,RH,NaN,NaN,NaN,NaN
3,date_adm,biodata,NaN,text,Admission Date,NaN,(For Empty Date type 1913-01-01),date_ymd,NaN,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
4,date_discharge,biodata,NaN,text,Date of discharge/death,NaN,(For Empty Date type 1913-01-01),date_ymd,2013-09-15,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
5,hosp_id,biodata,NaN,dropdown,Hospital ID,"66, Busia District Hospital",NaN,NaN,NaN,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
6,leave_period,biodata,NaN,yesno,Is leave period?,NaN,ONLY select yes during leave!,NaN,NaN,NaN,NaN,NaN,NaN,RH,NaN,NaN,NaN,NaN
7,random,biodata,NaN,radio,Randomized?,"1, Minimum | 2, Full Dataset",NaN,NaN,NaN,NaN,NaN,([hosp_id] = '51' and [hosp_id] = '53') and (...,y,RH,NaN,NaN,NaN,NaN
8,depid,biodata,NaN,text,Data Entry Person ID,NaN,Eg. 02,NaN,NaN,NaN,NaN,[hosp_id] = '51' and [hosp_id] = '52' and [hos...,NaN,NaN,NaN,NaN,NaN,NaN
9,date_today,biodata,NaN,text,Today's Date,NaN,NaN,date_ymd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@TODAY @HIDDEN
10,timestamp,biodata,NaN,text,Timestamp,NaN,NaN,datetime_ymd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@NOW @HIDDEN
11,ipno,biodata,NaN,text,Patients IPNO,NaN,input -1 for empty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,child_sex,biodata,NaN,radio,Gender,"0, Female | 1, Male | -1, Empty",NaN,NaN,NaN,NaN,NaN,NaN,NaN,RH,NaN,NaN,NaN,NaN
13,age_recorded,biodata,NaN,radio,Age Recorded?,"1, Yes | 2, No | 3, Empty",NaN,NaN,NaN,NaN,NaN,NaN,NaN,RH,NaN,NaN,NaN,NaN
14,age_less1mnth,biodata,NaN,yesno,Age less than 1 month,NaN,NaN,NaN,NaN,NaN,NaN,[age_recorded] = '1',y,RH,NaN,NaN,NaN,NaN
15,age_days,biodata,NaN,text,Age (Days),NaN,input -1 for empty,number,0,30.0,NaN,[age_less1mnth]='1',NaN,NaN,NaN,NaN,NaN,NaN
16,age_years,biodata,NaN,text,Age (years),NaN,input -1 for empty,number,0,18.0,NaN,[age_less1mnth] = '0',y,NaN,NaN,NaN,NaN,NaN
17,age_mths,biodata,NaN,text,Age (months),NaN,input -1 for empty,number,0,60.0,NaN,[age_less1mnth] = '0',y,NaN,NaN,NaN,NaN,NaN
18,is_minimum,biodata,NaN,calc,Is record minimum,if(([surgical_burns]='1') or ([doc_source]='2'...,DO NOT CHANGE!!!,NaN,NaN,NaN,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
19,res_loc,biodata,NaN,text,Residence - Location/Sub-Location,NaN,Input -1 for empty,NaN,NaN,NaN,NaN,[hosp_id] = '51' and [hosp_id] = '52',NaN,NaN,NaN,NaN,NaN,NaN
20,res_dst,biodata,NaN,text,Residence - District,NaN,Input -1 for empty,NaN,NaN,NaN,NaN,[hosp_id] = '52' and [hosp_id] = '51',NaN,NaN,NaN,NaN,NaN,NaN
21,ref_hosp,biodata,NaN,radio,Referred to hospital?,"1,Yes |0, No| -1, Empty",NaN,NaN,NaN,NaN,NaN,NaN,y,RH,NaN,NaN,NaN,NaN
22,ref_hosp_spec,biodata,NaN,text,Referred from which facility?,NaN,NaN,NaN,NaN,NaN,NaN,[hosp_id] = '51' and [hosp_id] = '52' and [hos...,NaN,NaN,NaN,NaN,NaN,NaN
23,readm_hosp,biodata,NaN,radio,Re-admission to this hospital?,"1, Yes | 0, No | -1, Empty",NaN,NaN,NaN,NaN,NaN,NaN,NaN,RH,NaN,NaN,NaN,NaN
24,readmin_hosp_dcs,biodata,NaN,radio,Discharged < 1 Month Ago?,"1, Yes | 0, No | -1, Empty",NaN,NaN,NaN,NaN,NaN,[readm_hosp] = '1',NaN,RH,NaN,NaN,NaN,NaN
25,weight,biodata,NaN,text,Weight (kgs),NaN,kgs ( enter -1 if not recorded),number,1,60.0,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
26,height,biodata,NaN,text,Height / Length (cm),NaN,cm; ( enter -1 if not recorded),number,40,160.0,NaN,[is_minimum] = '0',NaN,NaN,NaN,NaN,NaN,NaN
27,whz,biodata,NaN,dropdown,Weight-Height Z score,"1, 3SD | 2, 2SD | 3, 1SD | 4, 0SD | 5, -1SD | ...",NaN,NaN,NaN,NaN,NaN,[is_minimum] = '0',NaN,NaN,NaN,NaN,NaN,NaN
28,muac,biodata,NaN,text,MUAC (Mid-upper arm circumference),NaN,"(enter -1 if not recorded,enter data in cm)",number,5,25.0,NaN,NaN,y,NaN,NaN,NaN,NaN,NaN
29,vacc_source,biodata,NaN,radio,Vaccination/Immunization data source,"1, PAR | 2, Free text | -1, Empty",NaN,NaN,NaN,NaN,NaN,NaN,NaN,RH,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,dsc_dx2_pneum,discharge_information,NaN,dropdown,Pneumonia,"2, J18.9B-Pneumonia(severe) | 3, J18.9A-Pneumo...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
413,dsc_dx2_diarrhoea,discharge_information,NaN,dropdown,Diarrhoea / Acute GE (Gastro-Enteritis),"1, A09.0-Diarrhoea(Non-bloody) | 2, A09.8-Diar...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
414,dsc_dx2_dehydrat,discharge_information,NaN,dropdown,Dehydration,"1, R57.1-Shock | 2, E86.8-Severe | 3, E86.7-So...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
415,dsc_dx2_hiv,discharge_information,NaN,dropdown,HIV / AIDS,"3, B24-HIV +ve | 4, R75-Exposed/PMTCT+ | 5, HI...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
416,dsc_dx2_malnutr,discharge_information,NaN,dropdown,Malnutrition,"5, E44.1-Mild | 6, E44.0-moderate | 1, E40-Kwa...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
417,dsc_dx2_anaemia,discharge_information,NaN,dropdown,Anaemia,"1, D64.9B-Severe Anaemia | 2, D64.9A-Anaemia(N...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
418,dsc_dx2_meningitis,discharge_information,NaN,yesno,Meningitis,NaN,NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH,NaN,NaN,NaN,NaN
419,dsc_dx2_rickets,discharge_information,NaN,yesno,Rickets,NaN,NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH,NaN,NaN,NaN,NaN
420,dsc_dx2_asthma,discharge_information,NaN,dropdown,Asthma,"1, J46-Asthma-very severe | 2, J45.9B-Asthma-S...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
421,dsc_dx2_tb,discharge_information,NaN,dropdown,TB,"1, Pulmonary TB | 2, Extra-Pulmonary TB",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH,NaN,NaN,NaN,NaN
422,dsc_dx2_sepsis,discharge_information,NaN,yesno,Neonatal sepsis,NaN,NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH,NaN,NaN,NaN,NaN
423,dsc_dx2_pre_lbw,discharge_information,NaN,yesno,Prematurity / LBW,NaN,NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH,NaN,NaN,NaN,NaN
424,dsc_dx2_sickle_cell,discharge_information,NaN,yesno,Sickle cell disease,NaN,NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,RH,NaN,NaN,NaN,NaN
425,dsc_dx2_other_1,discharge_information,NaN,dropdown,Other secondary discharge diagnoses 1,"2, ACUTE ABDOMEN | 29, Acute respiratory infec...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1' and [hosp_id]='51' and [hosp_i...,NaN,NaN,NaN,NaN,NaN,NaN
426,dsc_dx2_other_2,discharge_information,NaN,dropdown,Other secondary discharge diagnoses 2,"2, ACUTE ABDOMEN | 29, Acute respiratory infec...",NaN,NaN,NaN,NaN,NaN,[dsc_dx2] = '1' and [hosp_id]='51' and [hosp_i...,NaN,NaN,NaN,NaN,NaN,NaN
427,dsc_dx2_other_3,discharge_information,NaN,dropdown,Other secondary discharge diagnoses 3,"2, ACUTE ABDOMEN | 29, Acute respiratory infec...",NaN,NaN,NaN,NaN,NaN,[hosp_id]='51' and [hosp_id]='53',NaN,NaN,NaN,NaN,NaN,NaN
428,dsc_dx2_other_4,discharge_information,NaN,sql,Other secondary discharge diagnoses 4,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
429,dsc_dx2_other_5,discharge_information,NaN,sql,Other Secondary Discharge Diagnoses 5,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
430,dsc_dx2_other_6,discharge_information,NaN,sql,Other Secondary Discharge Diagnoses 6,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
431,dsc_dx2_other_7,discharge_information,NaN,sql,Other Secondary Discharge Diagnoses 7,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_dx2] = '1',NaN,NaN,NaN,NaN,NaN,NaN
432,dsc_rx,discharge_information,Discharge treatment,yesno,Discharge treatment prescribed,NaN,NaN,NaN,NaN,NaN,NaN,[is_minimum] = '0' and [outcome] = '1',NaN,RH,NaN,NaN,NaN,NaN
433,dsc_rx1,discharge_information,NaN,sql,Discharge treatment1,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_rx] = '1',NaN,NaN,NaN,NaN,NaN,NaN
434,dsc_rx2,discharge_information,NaN,sql,Discharge treatment2,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_rx] = '1',NaN,NaN,NaN,NaN,NaN,NaN
435,dsc_rx3,discharge_information,NaN,sql,Discharge treatment3,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_rx] = '1',NaN,NaN,NaN,NaN,NaN,NaN
436,dsc_rx4,discharge_information,NaN,sql,Discharge treatment4,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_rx]='1',NaN,NaN,NaN,NaN,NaN,NaN
437,dsc_rx5,discharge_information,NaN,sql,Discharge treatment5,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_rx] = '1',NaN,NaN,NaN,NaN,NaN,NaN
438,dsc_rx_other1,discharge_information,NaN,sql,Discharge treatment_other1,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_rx]='1',NaN,NaN,NaN,NaN,NaN,NaN
439,dsc_rx_other2,discharge_information,NaN,sql,Discharge treatment_other2,select value from redcap_data where project_id...,NaN,autocomplete,NaN,NaN,NaN,[dsc_rx]='1',NaN,NaN,NaN,NaN,NaN,NaN
440,rx_nt_listed,discharge_information,NaN,yesno,Other discharge treatment not listed but docum...,NaN,NaN,NaN,NaN,NaN,NaN,[dsc_rx]='1',NaN,RH,NaN,NaN,NaN,NaN
441,rx_free_text,discharge_information,NaN,text,Other discharge treatment not listed,NaN,Separate with a comma if more than one.,NaN,NaN,NaN,NaN,[rx_nt_listed] = '1',NaN,RH,NaN,NaN,NaN,NaN

In [19]:

compare = datacompy.Compare(dataframes[1],dataframes[2],on_index=True)

In [20]:
compare.matches(ignore_extra_columns=False)

False

In [3]:
# This method prints out a human-readable report summarizing and sampling differences
print(type(compare.report()))

NameError: name 'compare' is not defined

In [23]:
#get columns unique to df1
compare.df2_unq_columns()

set()

In [25]:

compare.df2_unq_rows

,variable / field name,form name,section header,field type,field label,"choices, calculations, or slider labels",field note,text validation type or show slider number,text validation min,text validation max,identifier?,branching logic (show field only if...),required field?,custom alignment,question number (surveys only),matrix group name,matrix ranking?,field annotation
442,rx_free_text,discharge_information,NaN,text,Other discharge treatments not listed,NaN,NaN,NaN,NaN,NaN,NaN,[rx_nt_listed] = '1',NaN,RH,NaN,NaN,NaN,NaN

In [26]:
datacompy.core.render(df2)

TypeError: join() argument must be str or bytes, not 'DataFrame'